### ISSUE TITLE
兼容性支持pyecharts 1.0.0

### ISSUE THREAD

**Issue by liuyang1** [refraction-ray/xalpha#1]
pyecharts在1.0.0版本，修改了API接口。导致现在的依赖无法满足。

目前发现的典型改动为

    from pyecharts import Line

改为

    from pyecharts.char import Line

请考虑是限制支持到老版本的pyecharts（早于1.0.0), 或者跟进到新的版本？

关于pyecharts的具体改动，参见：https://github.com/pyecharts/pyecharts/issues/892

**Comment by refraction-ray** [comment]
(1a91b70a6e914802c822fbfd1d53190333e8aa64) head 已修复，改为支持 pyecharts 1+,
