### ISSUE TITLE
backtest.Balance策略做成封闭组合时报错：the initial total cash is too low

### ISSUE THREAD

**Issue by happyTonakai** [refraction-ray/xalpha#100]
```
import xalpha as xa
import pandas as pd

fundlist = ["002146", "001316", "001182"]
portfolio_dict = {"F" + f: 1 / len(fundlist) for f in fundlist}
check_dates = pd.date_range("2019-01-01", "2020-08-01", freq="Q")
bt = xa.backtest.Balance(
    start=pd.Timestamp("2019-01-04"),
    totmoney=10000,
    check_dates=check_dates,
    portfolio_dict=portfolio_dict,
    verbose=True,
)

bt.backtest()
sys = bt.get_current_mul()
sysfix = bt.get_current_mulfix()
```

始终报错 `the initial total cash is too low`，我看了下multiple.py里面似乎有10w这个数值，

于是改成 `sysfix = bt.get_current_mulfix(totmoney=100000)` 

结果通过`sysfix.v_positions_history()`发现剩余的数额都买入了货币基金

请问哪里出了问题呀？

**Comment by refraction-ray** [comment]
你用 bt.get_current_mulfix(totmoney=10000.1) 试一下呢，有时候就是组合交易四舍五入啥的，导致最早的钱totmoney会少一点点

**Comment by happyTonakai** [comment]
10000.1不行，10001可以
btw fundlist如果有6只基金的话这个值要设置到10010

**Comment by refraction-ray** [comment]
需要这么大的零头的话，可能里面还是有点小问题，我有空再看下。

**Comment by happyTonakai** [comment]
ok，那我reopen了。
还发现这个数值和check_dates的长度有关，6只基金的组合半年做一次动态平衡10010是可以的，但是改为3个月做一次平衡就需要10015了。

**Comment by refraction-ray** [comment]
最近有空看了一下这个问题。其原因在于，每次做动态平衡时，卖出对应的份额是用需要平衡的金额除以净值计算的，没有考虑赎回费（也比较难精确考虑），这样每次再平衡的时候，实际上买的多，卖出得到的少，所以还需要初始金额额外的部分。现在把代码修正成了考虑千分之五的赎回费，这样大部分时候初始金额就够了，代价是再平衡之后可能有一些货币基金的零头。
