### ISSUE TITLE
请问基金有没有查询到该基金对应规模到Api 

### ISSUE THREAD

**Issue by bobbypiggy** [refraction-ray/xalpha#101]
在class fundinfo(basicinfo):等几个里面找了一下没有找到，希望可以查询某个基金等规模：xxx亿元。

**Comment by refraction-ray** [comment]
``xa.get_rt("F501018")`` 返回的字典里有 scale

**Comment by bobbypiggy** [comment]
好使，谢谢：
{'name': '南方原油A',
 'time': '2021-02-18',
 'current': 0.6984,
 'market': 'CN',
 'currency': 'CNY',
 'current_ext': None,
 'status': '暂停申购  (单日累计购买上限2000元)',
 'type': 'QDII',
 'scale': '15.96亿元（2020-12-31）',
 'manager': '黄亮',
 'company': '南方基金',
 'estimate': None,
 'estimate_time': None}
