### ISSUE TITLE
请问哪里可以获取到基金的发行时间？

### ISSUE THREAD

**Issue by bobbypiggy** [refraction-ray/xalpha#103]
这个api调用得到的时间是当天的时间

例如：xa.get_rt("F"+'001216')
{'name': '易方达新收益混合A',
 **'time': '2021-03-03',**
 'current': 4.071,
 'market': 'CN',
 'currency': 'CNY',
 'current_ext': None,
 'status': '开放申购',
 'type': '混合型',
 'scale': '15.60亿元（2020-12-31）',
 'manager': '张清华',
 'company': '易方达基金',
 'estimate': 4.0738,
 'estimate_time': '2021-03-03 15:00'}

**Comment by bobbypiggy** [comment]
'time': '2021-03-03',

**Comment by refraction-ray** [comment]
```
yfd = xa.fundinfo("001216")
yfd.price.iloc[0]["date"]
```

**Comment by bobbypiggy** [comment]
验证成功：
yfd = xa.fundinfo("001216")
yfd.price.iloc[0]["date"]
Timestamp('2015-04-17 00:00:00')

和ttjj一致：

基金类型：混合型  \|  中高风险 | 基金规模：15.60亿元（2020-12-31） | 基金经理：张清华
-- | -- | --
成 立 日：2015-04-17 | 管 理 人：易方达基金 |

**Comment by bobbypiggy** [comment]
可以了。
