### ISSUE TITLE
指数型基金api使用的疑问

### ISSUE THREAD

**Issue by bobbypiggy** [refraction-ray/xalpha#104]
通过调用得到基金，按理说指数型基金：如 工银中证京津冀协同发展指数C(164825)
p = xa.misc.get_fund_list('zs')

但是调用这个api不行：
fund_num = 'SH164825'
fund_info = xa.indexinfo(fund_num)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-18-bb247d3a8164> in <module>
      1 fund_num = 'SH004069'
----> 2 fund_info = xa.indexinfo(fund_num)

~/opt/anaconda3/lib/python3.7/site-packages/xalpha/info.py in __init__(self, code, value_label, fetch, save, path, form)
   1239         )
   1240         super().__init__(
-> 1241             code, value_label=value_label, fetch=fetch, save=save, path=path, form=form
   1242         )
   1243 

~/opt/anaconda3/lib/python3.7/site-packages/xalpha/info.py in __init__(self, code, fetch, save, path, form, round_label, dividend_label, value_label)
    369         self.format = form
    370         if fetch is False:
--> 371             self._basic_init()  # update self. name rate and price table
    372         else:
    373             try:

~/opt/anaconda3/lib/python3.7/site-packages/xalpha/info.py in _basic_init(self)
   1246         cr = csv.reader(raw.text.splitlines(), delimiter=",")
   1247         my_list = list(cr)
-> 1248         factor = float(my_list[-1][3])
   1249         dd = {
   1250             "date": [

ValueError: could not convert string to float: '收盘价'

得调用普通基金的api：
fund_num = '164825'
fund_info = xa.fundinfo(fund_num, **ioconf)

**Comment by refraction-ray** [comment]
这个 API 是给指数用的，不是指数基金用的，指数基金也是基金，直接 `fundinfo("004069")` 就好了

**Comment by bobbypiggy** [comment]
理解了，谢谢。
