### ISSUE TITLE
get_portfolio_holdings测试问题

### ISSUE THREAD

**Issue by bobbypiggy** [refraction-ray/xalpha#106]
fund_num = '005461'
fund_info = xa.fundinfo(fund_num)

fund_info.get_portfolio_holdings()
{'stock_ratio': **19.71**, 'bond_ratio': **100.35**, 'cash_ratio': 2.19}

get_portfolio_holdings调用返回的占比不对：

从get_stock_holdings查询的信息可以看出：股票的占比是10.99，债券的占比是68.17，和ttjj网页一致；
http://fund.eastmoney.com/005461.html?spm=search

	code	name	ratio	share	value
0	601601	中国太保	1.58	72.38	2779.39
1	603501	韦尔股份	1.22	9.32	2153.85
2	002027	分众传媒	1.17	208.47	2057.58
3	688002	睿创微纳	1.14	18.15	2014.63
4	300122	智飞生物	1.04	12.39	1832.60
5	000661	长春高新	0.99	3.90	1750.75
6	300750	宁德时代	0.99	4.98	1748.53
7	600741	华域汽车	0.97	58.99	1700.09
8	002415	海康威视	0.95	34.47	1672.27
9	603658	安图生物	0.94	11.40	1655.18

	code	name	ratio	value
0	113011	光大转债	9.31	68.17
1	113013	国君转债	5.74	68.17
2	127005	长证转债	4.75	68.17
3	128095	恩捷转债	3.55	68.17
4	110061	川投转债	3.53	68.17
5	128028	赣锋转债	3.17	68.17
6	128046	利尔转债	3.10	68.17
7	132021	19中电EB	3.06	68.17
8	113583	益丰转债	2.91	68.17
9	128112	歌尔转2	2.72	68.17
10	113582	火炬转债	2.69	68.17
11	123044	红相转债	2.61	68.17
12	132018	G三峡EB1	2.52	68.17
13	127011	中鼎转2	2.39	68.17
14	128017	金禾转债	2.20	68.17
15	113009	广汽转债	2.14	68.17
16	123017	寒锐转债	2.12	68.17
17	110069	瀚蓝转债	2.03	68.17
18	113588	润达转债	1.45	68.17
19	110066	盛屯转债	1.28	68.17
20	123049	维尔转债	1.01	68.17
21	113035	福莱转债	1.01	68.17
22	113548	石英转债	0.91	68.17
23	113579	健友转债	0.79	68.17
24	128065	雅化转债	0.79	68.17
25	113014	林洋转债	0.39	68.17

**Comment by refraction-ray** [comment]
股债占比，可以参考 http://fundf10.eastmoney.com/zcpz_005461.html，
`{'stock_ratio': 19.71, 'bond_ratio': 100.35, 'cash_ratio': 2.19}` 似乎是对的，超过100是因为债券部分有杠杆。下边这个用具体持仓来分析股债比例的逻辑我没有太懂，是把持仓显示的各个标的的比例简单加起来吗？

**Comment by bobbypiggy** [comment]
对：就是将持仓显示的各个标的的比例简单加起来：
股票：sum(1.58 | 1.22 | 1.17 | 1.14 | 1.04 | 0.99 | 0.99 | 0.97 | 0.95 | 0.94 | )=10.99%
债券：也是类似的累加得到68.17%；

**Comment by refraction-ray** [comment]
那这个数据应该没有我上边网页直接披露的数据准确。一来是持仓可能不全，二来可能杠杆的考虑也有些问题
