### ISSUE TITLE
【需求】建议增加指数基金的pe等获取

### ISSUE THREAD

**Issue by bobbypiggy** [refraction-ray/xalpha#109]
需求描述：建议增加指数基金估值之**PE, PB, ROE**等获取，基金定投选择低估的时候买入，估值适中的时候持有，高估时候卖出。

用于计算PE/PB百分位：这个指标是跟历史数据比较，看看现在的数据是在一个什么区域。
百分位5%，代表现在的估值比过去95%的时间低。

**Comment by bobbypiggy** [comment]
https://zhuanlan.zhihu.com/p/55933552

**Comment by refraction-ray** [comment]
你说的这些现在都是有的, `xa.get_daily("peb-SH000300")`,`xa.PEBHistory("SH000300")`

**Comment by bobbypiggy** [comment]
看到帮助了，之前漏了这个：
一行拿到指数，行业，基金和个股的历史估值和即时估值分析（指数部分需要聚宽数据，本地试用申请或直接在聚宽云平台运行）

xa.PEBHistory("SH000990").summary()
xa.PEBHistory("F100032").v()

需要聚宽：
DataSourceNotFound: Data source jq is not authenticated
