### ISSUE TITLE
v_tradevolume的兼容性问题

### ISSUE THREAD

**Issue by bobbypiggy** [refraction-ray/xalpha#110]
bear_fund.v_tradevolume(freq='W') 

显示如下错误信息：
/Users/tgz/opt/anaconda3/lib/python3.7/site-packages/xalpha/trade.py:126: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated.  Please use Series.dt.isocalendar().week instead.
  cfmerge = cftable.groupby([cftable["date"].dt.year, cftable["date"].dt.week])[

**Comment by refraction-ray** [comment]
没看懂，你是指 bear_fund 没有交易数据吗，那画图报错也是正常行为吧，画出个空图框也没啥意思

**Comment by bobbypiggy** [comment]
FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated. Please use Series.dt.isocalendar().week instead.

cfmerge = cftable.groupby([cftable["date"].dt.year, cftable["date"].dt.week])

对于python3.7，Series.dt.week是不是应该换成这个：Series.dt.isocalendar().week

**Comment by refraction-ray** [comment]
> 对于python3.7，Series.dt.week是不是应该换成这个：Series.dt.isocalendar().week

看起来这个应该是高版本 pandas 的要求，和 python 版本似乎没关系，可以考虑在未来某个时间点换掉。这里面有不同API对周的定义不太一样的问题，比如这里提到的内容，https://github.com/refraction-ray/xalpha/blob/6733640263502123815b24c0d0b1ef6b4c1f28f1/xalpha/trade.py#L136-L149
我暂时还没仔细研究这个 API 替换是否有区别。

**Comment by bobbypiggy** [comment]
好，先关闭了。
