### ISSUE TITLE
correlation_table这个方法有将self.totprice 开始日期对齐吗？

### ISSUE THREAD

**Issue by bobbypiggy** [refraction-ray/xalpha#111]
1.correlation_table方法的结束日期用“end”对齐了，起始日期有对齐吗？

def correlation_table(self, end=yesterdayobj()):
        """
        give the correlation coefficient amongst referenced funds and indexes

        :param end: string or object of date, the end date of the line
        :returns: pandas DataFrame, with correlation coefficient as elements
        """
        partprice = **self.totprice[self.totprice["date"] <= end]**
        covtable = partprice.iloc[:, 1:].pct_change().corr()
        return covtable

**Comment by refraction-ray** [comment]
看源码就知道了 https://github.com/refraction-ray/xalpha/blob/6733640263502123815b24c0d0b1ef6b4c1f28f1/xalpha/evaluate.py#L30-L40
开始日期是对齐的
