### ISSUE TITLE
有api可以查询到ETF场外连接基金的净值等信息么？

### ISSUE THREAD

**Issue by bobbypiggy** [refraction-ray/xalpha#114]
现在xalpha已经可以查询股票、混合、债券类等，有api可以查询到ETF场外连接基金的净值等信息么？

**Comment by bobbypiggy** [comment]
xa.misc.get_fund_list('etf') 查不到

**Comment by refraction-ray** [comment]
xa.misc.get_fund_list('zs') 可以列出指数基金，但不一定是 etf 连接，也可能是 lof 或单纯的指数基金

**Comment by bobbypiggy** [comment]
这些我了解，也一直在用xalpha来获取基金list。 

但是天天基金上的“ETF联接”是分开的；
http://fund.eastmoney.com/LJ_jzzzl.html#os_0;isall_0;ft_;pt_11

**Comment by refraction-ray** [comment]
这个似乎和现在 get_fund_list 的接口并不是一个 API。现在的函数不太能支持

**Comment by bobbypiggy** [comment]
那先关闭吧；

**Comment by bobbypiggy** [comment]
有300多支ETF基金，今天简单测试了一下：

# %%
html_doc = 'http://fund.eastmoney.com/LJ_jzzzl.html#os_0;isall_0;ft_;pt_11'

headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36"
    }
url = "http://fund.eastmoney.com/Data/Fund_JJJZ_Data.aspx"
params = {
    "t": "1",
    "lx": "1",
    "letter": "",
    "gsid": "",
    "text": "",
    "sort": "zdf,desc",
    "page": "1,20000",
    "dt": "1580914040623",
    "atfc": "",
    "onlySale": "0",
}
res = requests.get(url, params=params, headers=headers)

df_etf = pd.read_html(html_doc)[2]

**Comment by bobbypiggy** [comment]
今天简单试验了一下，有300多支ETF基金：
# %%
html_doc = 'http://fund.eastmoney.com/LJ_jzzzl.html#os_0;isall_0;ft_;pt_11'
df_etf = pd.read_html(html_doc)[2]
