### ISSUE TITLE
建议账单增加一行，可以用来写基金编码对应的名称

### ISSUE THREAD

**Issue by bobbypiggy** [refraction-ray/xalpha#119]
xa.record的初始化函数建议增加skiprows=1：
def __init__(
        self, path="input.csv", format="matrix", fund_property=False, **readkwds
    ):
        if isinstance(path, str):
            df = pd.read_csv(path, **readkwds, skiprows=1)

这样账单csv文件可以写成这样：

  **| 易方达新收益混合A | 华夏聚利债券 | 华宝中证医疗指数 | 鹏扬汇利债券C | 景顺中证500行业中性低波动 | 招商产业债券A | 天弘文化新兴产业 | 国富大中华精选混合**
-- | -- | -- | -- | -- | -- | -- | -- | --
date | 1216 | 14 | 162412 | 4586 | 3318 | 217022 | 164205 | 934
20210222 | 500 | 0 | 0 |   |   |   |   |  
20210302 | 500 | 0 | 0 |   |   |   |   |

**Comment by refraction-ray** [comment]
现在也可以啊， readkws 都可以传进去

**Comment by bobbypiggy** [comment]
喔，没有注意到。谢谢。
