### ISSUE TITLE
xa.PEBHistory 运行的错误

### ISSUE THREAD

**Issue by bobbypiggy** [refraction-ray/xalpha#120]
h=xa.PEBHistory("SH000050", start="2013-01-01")

KeyError                                  Traceback (most recent call last)
~/opt/anaconda3/lib/python3.7/site-packages/xalpha/universal.py in wrapper(*args, **kws)
   1945                         elif backend == "memory":
-> 1946                             df0 = getattr(thismodule, "cached_dict")[key]
   1947                         else:

KeyError: 'peb-SH000050'

During handling of the above exception, another exception occurred:

ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-5-6fdf2f1ce4c8> in <module>
----> 1 h=xa.PEBHistory("SH000050", start="2013-01-01")

~/opt/anaconda3/lib/python3.7/site-packages/xalpha/toolbox.py in PEBHistory(code, start, end)
    156     """
    157     if code.startswith("SH000") or code.startswith("SZ399"):
--> 158         return IndexPEBHistory(code, start, end)
    159     elif code.startswith("F"):
    160         return FundPEBHistory(code, start, end)

~/opt/anaconda3/lib/python3.7/site-packages/xalpha/toolbox.py in __init__(self, code, start, end)
    221         if not end:
    222             end = yesterday_str
--> 223         self.df = xu.get_daily("peb-" + self.scode, start=self.start, end=end)
    224         self.ratio = None
    225         self.title = "指数"

~/opt/anaconda3/lib/python3.7/site-packages/xalpha/universal.py in wrapper(*args, **kws)
   2002                                 ).strftime("%Y%m%d")
   2003                         is_changed = True
-> 2004                         df0 = f(*args, **kws)
   2005 
   2006                 if df0 is not None and len(df0) > 0 and is_changed:

~/opt/anaconda3/lib/python3.7/site-packages/xalpha/universal.py in _get_daily(code, start, end, prev, _from, wrapper, handler, **kws)
   1108             or code.startswith("000")
   1109         ):
-> 1110             df = _get_peb_range(code=code, start=start_str, end=end_str)
   1111         elif code.startswith("F"):
   1112             df = get_fund_peb_range(code=code, start=start, end=end)

~/opt/anaconda3/lib/python3.7/site-packages/xalpha/provider.py in wrapper(*args, **kws)
    102         def wrapper(*args, **kws):
    103             if getattr(thismodule, s + "_auth", False):
--> 104                 return f(*args, **kws)
    105             else:
    106                 raise DataSourceNotFound("Data source %s is not authenticated" % s)

~/opt/anaconda3/lib/python3.7/site-packages/xalpha/universal.py in _get_peb_range(code, start, end)
   2130         data["date"].append(d)
   2131         logger.debug("compute pe pb on %s" % d)
-> 2132         r = get_peb(code, date=d.strftime("%Y-%m-%d"))
   2133         data["pe"].append(r["pe"])
   2134         data["pb"].append(r["pb"])

~/opt/anaconda3/lib/python3.7/site-packages/xalpha/provider.py in wrapper(*args, **kws)
    102         def wrapper(*args, **kws):
    103             if getattr(thismodule, s + "_auth", False):
--> 104                 return f(*args, **kws)
    105             else:
    106                 raise DataSourceNotFound("Data source %s is not authenticated" % s)

~/opt/anaconda3/lib/python3.7/site-packages/xalpha/universal.py in get_peb(index, date, table)
   2346     if table:
   2347         return df
-> 2348     return {"pe": round(100.0 / tote, 3), "pb": round(100.0 / totb, 3)}
   2349 
   2350 

ZeroDivisionError: float division by zero

**Comment by refraction-ray** [comment]
github 上的最新版有关于该类型问题的修复，但不确定能不能解决这个具体的问题，该修复暂时还没有发布到 pypi

**Comment by bobbypiggy** [comment]
等待发布后回归。
