### ISSUE TITLE
建议代码里面增加一点数据清洗的选项

### ISSUE THREAD

**Issue by bobbypiggy** [refraction-ray/xalpha#121]
统计一下数据里面缺失情况，发现经常有缺失数据项，会影响后面对收益计算：

df_report.isnull().sum()
易方达新收益混合A          0
华夏聚利债券             0
华宝中证医疗指数           0
**国富大中华精选混合          1**
景顺中证500行业中性低波动     0
招商产业债券A            0
天弘文化新兴产业           0
**鹏扬汇利债券C           24**
建信稳定得利债券A          0
dtype: int64

建议代码里面增加一点数据清洗的选项，比如对丢失数据进行填充：
df = df.fillna(method='ffill')

https://zhuanlan.zhihu.com/p/60241672

**Comment by refraction-ray** [comment]
没太懂，是什么数据有缺失

**Comment by bobbypiggy** [comment]
国富大中华精选混合 和 鹏扬汇利债券C  这2支基金有缺值，跑xalpha的api统计收益率会有异常。

**Comment by bobbypiggy** [comment]
比如“国富大中华精选混合”的累积净值在今年的2月9日-16日之间由于放假没有值

**Comment by bobbypiggy** [comment]
比如“国富大中华精选混合”的累积净值在今年的2月9日-16日之间由于放假没有值

**Comment by refraction-ray** [comment]
这个填充了也不是正确的，还不如保持和天天基金数据源原样一致，另外xalpha所有的计算应该都不会依赖于累计净值这一项，因为这个量本来就没什么意义，收益率计算不会异常

**Comment by bobbypiggy** [comment]
了解，谢谢。
