### ISSUE TITLE
xa.fundinfo 的warning？

### ISSUE THREAD

**Issue by bobbypiggy** [refraction-ray/xalpha#122]
调用：xa.fundinfo('006733')
显示：
warning: this fund has no data for rate
博时创业板ETF联接C

http://fund.eastmoney.com/006733.html?spm=search

**Comment by bobbypiggy** [comment]
看了一下都是C类型的基金有问题。

**Comment by refraction-ray** [comment]
这个报错的意思是对应基金抓取不到申购费的信息，这种情况默认申购费为0， 倒是和 c 类基金相符，因此不会出现错误，只是一个提醒，防止有其他基金抓取不到费用没注意到

**Comment by bobbypiggy** [comment]
了解了，谢谢。
