### ISSUE TITLE
老哥，你可以留个捐赠二维码的。

### ISSUE THREAD

**Issue by onion1003** [refraction-ray/xalpha#127]
挺感谢你的项目的，可以留个二维码，请你喝杯咖啡表示感谢，嘻嘻(*^__^*) 。

**Comment by refraction-ray** [comment]
谢谢好意。不过总觉得接受了捐赠就要对这个项目更负责，这方面我实在不敢保证，因此就不开放捐赠了。就像最近我就比较忙，很多问题也没时间修复或者开放。如果接受了捐赠，这方面会有些心理压力，而现在就比较自由。
