### ISSUE TITLE
warning: this fund has no data for rate

### ISSUE THREAD

**Issue by aaronyunzhao** [refraction-ray/xalpha#13]
xalpha.fundinfo('159928')
会出现如标题出错

**Comment by refraction-ray** [comment]
这个是程序自己的 warning，故意的，说明这基金申购费率是空，如果最后报错了那是赎回费率的处理也有问题，建议升级到最新版，这样不会有报错，只会有 warning，但不解决问题：这基金的申购赎回费率自动抓取不会有正确结果。基金类可以继续用，如果交易分析的话，只是做不到和实盘完全一致了，因为费率不完全正确。如果有强迫症，可以在 fundinfo 类生成后，用 info.rate=, info.feeinfo= 啥的手动设置正确的申购赎回费率。

**Comment by aaronyunzhao** [comment]
谢谢，明白了。
xalpha.fundinfo('481012')报错NameError: name 'null' is not defined，是否是类似？

**Comment by refraction-ray** [comment]
我的 481012 没有问题，你也可以升级最新版试下

**Comment by aaronyunzhao** [comment]
谢谢。升级到v0.8.7 - 2020.04.10后，
481012 没问题了
159928 提示`159928 赎回费信息异常，多是因为定开基金，封闭基金或场内 ETF: ['0.15%']`
