### ISSUE TITLE
xa.indexinfo接口无法使用

### ISSUE THREAD

**Issue by lillsi** [refraction-ray/xalpha#131]
发现网易的数据源打不开了，根据入门文档xa.info第一个介绍就是跑这个方法，但是却跑不动，想知道是不是我的环境或者版本出问题。

看其他issue，好像是都改用xa.get_daily替代？

**Comment by refraction-ray** [comment]
我这边测试，indexinfo 是可以正常运行的，你可以先试试其他函数有没有问题

**Comment by lillsi** [comment]
zzhli = xa.indexinfo('0000922') 

跑jupyter的返回结果
Fails at fetching url: http://quotes.money.163.com/service/chddata.html?code=0000922&start=19901219&end=20210619&fields=TCLOSE. Try again.
Fails at fetching url: http://quotes.money.163.com/service/chddata.html?code=0000922&start=19901219&end=20210619&fields=TCLOSE. Try again.
Fails at fetching url: http://quotes.money.163.com/service/chddata.html?code=0000922&start=19901219&end=20210619&fields=TCLOSE. Try again.
Fails at fetching url: http://quotes.money.163.com/service/chddata.html?code=0000922&start=19901219&end=20210619&fields=TCLOSE. Try again.
Fails at fetching url: http://quotes.money.163.com/service/chddata.html?code=0000922&start=19901219&end=20210619&fields=TCLOSE. Try again.
Still wrong at fetching url: http://quotes.money.163.com/service/chddata.html?code=0000922&start=19901219&end=20210619&fields=TCLOSE. after 5 tries.

网易的行情中心我这边打开也是返回空白页，其他接口能跑起来，刚上手学习，不太熟悉，谢谢分享。

**Comment by lillsi** [comment]
今早在公司里试一下又可以了，是网易数据源那边服务器报错

**Comment by whistorphi64** [comment]
同遇到这个问题，不过现在是这么报错
IndexError                                Traceback (most recent call last)
Cell In[13], line 1
----> 1 xa.indexinfo("SH000922")

File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\xalpha\info.py:1211, in indexinfo.__init__(self, code, value_label, fetch, save, path, form)
   1203 self.rate = 0
   1204 self._url = (
   1205     "http://quotes.money.163.com/service/chddata.html?code="
   1206     + code
   (...)
   1209     + "&fields=TCLOSE"
   1210 )
-> 1211 super().__init__(
   1212     code, value_label=value_label, fetch=fetch, save=save, path=path, form=form
   1213 )

File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\xalpha\info.py:342, in basicinfo.__init__(self, code, fetch, save, path, form, round_label, dividend_label, value_label)
    340 self.format = form
    341 if fetch is False:
--> 342     self._basic_init()  # update self. name rate and price table
    343 else:
    344     try:

File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\xalpha\info.py:1220, in indexinfo._basic_init(self)
   1218 cr = csv.reader(raw.text.splitlines(), delimiter=",")
   1219 my_list = list(cr)
-> 1220 factor = float(my_list[-1][3])
   1221 dd = {
   1222     "date": [
   1223         dt.datetime.strptime(my_list[i + 1][0], "%Y-%m-%d")
   (...)
   1230     "comment": [0 for _ in range(len(my_list) - 1)],
   1231 }
   1232 index = pd.DataFrame(data=dd)

IndexError: list index out of range
请问是不能用了吗
