### ISSUE TITLE
可转债 127035 报错

### ISSUE THREAD

**Issue by peterzhu001** [refraction-ray/xalpha#134]
由于JSL分年的利率最后少一个 “%”，数据取不全了，于是报错了。
我是手工加了一个%在最后，大神看下如何优雅的打个补丁吧。。。
JSL的数据貌似是手工COPY的。。。

**Comment by refraction-ray** [comment]
https://github.com/refraction-ray/xalpha/commit/febf420cacd80c4efa5ea817c987e1562cb5bdd7 应该已修复
