### ISSUE TITLE
这里的值是不是取错了呢？

### ISSUE THREAD

**Issue by lhq0826** [refraction-ray/xalpha#136]
https://github.com/refraction-ray/xalpha/blob/febf420cacd80c4efa5ea817c987e1562cb5bdd7/xalpha/info.py#L602
应该描述的是日涨幅信息吧，是不是应该用 equityReturn 呢？

**Comment by refraction-ray** [comment]
这个值是分红折算信息

**Comment by lhq0826** [comment]
@refraction-ray 那是我搞错了😄
