### ISSUE TITLE
请问封闭式基金的折价溢价率如何获取

### ISSUE THREAD

**Issue by sdu2011** [refraction-ray/xalpha#137]
查看了info.py和搜索issue  没有找到相关代码.   
```
import xalpha as xa
xa.set_backend(backend="csv", path="./lof", precached="20170101")

import logging
logger = logging.getLogger('xalpha')
logger.setLevel(logging.DEBUG)
ch = logging.StreamHandler()
ch.setLevel(logging.DEBUG)
logger.addHandler(ch)

code = '501085'
fund=xa.fundinfo(code)

fund.price #净值信息

fund.xx #如何获取价格信息？  溢价率？
```

我想回测类似动量策略,比如每隔xx天轮动一次,选取前n个净值增长最猛的封闭式基金,目前有没有现成的可参考的策略代码?   多谢作者！

**Comment by refraction-ray** [comment]
这个需求比较复杂，对于历史的净值和价格的话 fundinfo 对应的是净值，而 ``get_daily("SH123456")`` 对应的是每日的价格。比例可以计算溢价率。

而对于当日的净值预测，对于每天更新净值的封基，可以参考 API ``xa.RTPredict()``. 如果是按周或者更长周期更新一个净值的封基，可能暂时没什么好办法。但无论哪一种，都需要手动去提供对应的持仓标的和占比的字典。当然这一持仓，很多时候也可以通过程序化的方式获取 ``xa.get_fund_holdings``

至于动量轮动，暂时没有代码，不过可以参考 xa.backtest 中实现的其他轮动和动量策略结合一下即可。

**Comment by sdu2011** [comment]
> 这个需求比较复杂，对于历史的净值和价格的话 fundinfo 对应的是净值，而 `get_daily("SH123456")` 对应的是每日的价格。比例可以计算溢价率。
> 
> 而对于当日的净值预测，对于每天更新净值的封基，可以参考 API `xa.RTPredict()`. 如果是按周或者更长周期更新一个净值的封基，可能暂时没什么好办法。但无论哪一种，都需要手动去提供对应的持仓标的和占比的字典。当然这一持仓，很多时候也可以通过程序化的方式获取 `xa.get_fund_holdings`
> 
> 至于动量轮动，暂时没有代码，不过可以参考 xa.backtest 中实现的其他轮动和动量策略结合一下即可。

我研究一下,非常感谢!
