### ISSUE TITLE
请问支持可转债数据获取吗？

### ISSUE THREAD

**Issue by bobbypiggy** [refraction-ray/xalpha#139]
import xalpha as xa
df = xa.misc.get_ri_status()

这个似乎已经不太好使了。

**Comment by refraction-ray** [comment]
是的，富投网好像界面经常变，api 不太稳定，也没有继续支持的想法，建议使用类似的 ``get_jsl_cb_status``

**Comment by bobbypiggy** [comment]
了解，谢谢。
