### ISSUE TITLE
报错“'NoneType' object has no attribute 'groups'”

### ISSUE THREAD

**Issue by ym1137981594** [refraction-ray/xalpha#144]
nfyy = xa.fundinfo("519732")   
获取基金信息的，报错“'NoneType' object has no attribute 'groups'”，能请问下是为什么吗？

**Comment by refraction-ray** [comment]
我这边是没问题的，如果还有问题，请提供下软件版本信息和完整的脚本

**Comment by refraction-ray** [comment]
如果还有问题，可以再次 open issue
