### ISSUE TITLE
功能需求，请参考

### ISSUE THREAD

**Issue by jydcb003** [refraction-ray/xalpha#146]
您好，非常感谢您的这个项目，我在开始用的时候有个想法，能否在初始设置的时候直接设置当前的持仓成本净值和份额，这样今天之前的都不管了，从今天开始接下去继续算收益?这样就可以不用导入账单了吧?另外如果要导入账单，如果碰到一开始是选的现金分红，分红一次之后改成红利再投资，这样的账单要怎么填呢？感谢！

**Comment by refraction-ray** [comment]
对于初始持仓成本净值和份额设置，场内账单格式其实可以实现，场外账单格式暂时应该不太行，https://github.com/refraction-ray/xalpha/issues/135 也提及过该问题。

分红和红利再投可以每次单独设置，请参考文档 https://xalpha.readthedocs.io/en/latest/advance.html#id9：

> 2. 关于交易数字的一些特别约定，交易数字小数点一位之后的非零位有特别约定，不代表交易的部分。 小数点后第二位如果是5，且当日恰好为对应基金分红日，标志着选择了分红再投入的方式，否则默认分红拿现金。（该默认行为 property 含 2 时可翻转）比如 100.05 的意思是当日分红再投入且又申购了 500 元。

**Comment by jydcb003** [comment]
明白了，感谢😊
