### ISSUE TITLE
收益情况需求

### ISSUE THREAD

**Issue by jydcb003** [refraction-ray/xalpha#147]
请问xalpha支持查看基金或者组合近7天涨幅，近一个月｀近三个月涨幅 之类的吗？

**Comment by refraction-ray** [comment]
可以自己程序计算，因为 comb.summary("2021-11-10") 这种是可以查看每天的组合情况的，去不同日期的数据比一下就好了

**Comment by jydcb003** [comment]
好的(•̤̀ᵕ•̤́๑)ᵒᵏᵎᵎᵎᵎ感谢您答复!
