### ISSUE TITLE
获取指数信息出现乱码

### ISSUE THREAD

**Issue by laye0619** [refraction-ray/xalpha#149]
我是使用的版本是11.5
获取基金信息都是正常的，但是获取指数信息出现乱码，净值信息也是错误的。。。 所有指数都这样。
<img width="1120" alt="Screen Shot 2022-01-26 at 2 32 00 PM" src="https://user-images.githubusercontent.com/9484313/151115007-8247dc42-faad-4a45-8572-a1e9b730a9cf.png">

**Comment by refraction-ray** [comment]
可能和 https://github.com/refraction-ray/xalpha/pull/148 有关？这个代码应该还没发布到 pip 版本

**Comment by laye0619** [comment]
应该是这个问题，什么时候能发布到pip？

**Comment by refraction-ray** [comment]
v0.11.6 已发布
