### ISSUE TITLE
可转债数据获取报错

### ISSUE THREAD

**Issue by haydengao** [refraction-ray/xalpha#154]
xa.CBCalculator函数获取利率格式错误
ticker="SZ128025"
c=xa.CBCalculator(ticker)

Fetching url: https://www.jisilu.cn/data/convert_bond_detail/113600 . Inside function `__init__`
ValueError                                Traceback (most recent call last)
<ipython-input-185-35a7f17fccce> in <module>
      1 ticker="SH113600"
----> 2 c=xa.CBCalculator(ticker)

/opt/conda/lib/python3.8/site-packages/xalpha/toolbox.py in __init__(self, code, bondrate, riskfreerate, volatility, name, zgj)
    765         r.encoding = "utf-8"
    766         b = BeautifulSoup(r.text, "lxml")
--> 767         self.rlist = [
    768             float(re.search(r"[\D]*([\d]*.[\d]*)[\s]*[\%]*", s).group(1))
    769             for s in re.split("、|，", b.select("td[id=cpn_desc]")[0].string)

/opt/conda/lib/python3.8/site-packages/xalpha/toolbox.py in <listcomp>(.0)
    766         b = BeautifulSoup(r.text, "lxml")
    767         self.rlist = [
--> 768             float(re.search(r"[\D]*([\d]*.[\d]*)[\s]*[\%]*", s).group(1))
    769             for s in re.split("、|，", b.select("td[id=cpn_desc]")[0].string)
    770         ]

ValueError: could not convert string to float: '1%'
查了下代码，集思录的利率数据有可能是整数，后面就会没有小数点，导致代码搜索匹配错误
利率 | 第一年 0.4%，第二年 0.6%，第三年 1%，第四年 1.5%，第 五年 2.5%，第六年 3%
需要修改的文件是：toolbox.py的第767行

**Comment by refraction-ray** [comment]
> 原来的代码，小数点的匹配规则感觉修改一下就通用了
> 
> ```
> rlist = [
>             float(re.search(r"[\D]*([\d]*.[\d]*)[\s]*[\%]*", s).group(1))
>             for s in re.split("、|，", b.select("td[id=cpn_desc]")[0].string)
>         ]
> ```
> 
> 改为：
> 
> ```
> rlist = [
>             float(re.search(r"[\D]*([\d]*\.?[\d]*)[\s]*[\%]*", s).group(1))
>             for s in re.split("、|，", b.select("td[id=cpn_desc]")[0].string)
>         ]
> ```

似乎 % 要把 * 去掉才可以（不知道有没有没有 % 的匹配情况），不然搜索出来的部分会带 %

**Comment by refraction-ray** [comment]
最新 commit 已更新，但不确定是否仍会有情况 fail 掉，有待之后测试和观察
