### ISSUE TITLE
在csv中卖出的-266.65份额在ctable中变成-266.64的问题

### ISSUE THREAD

**Issue by kaharjan** [refraction-ray/xalpha#158]
006229中欧医疗创新股票， 2022年3月30日卖出份额是 266.65， 我在csv文件中写的也是-266.65， 但ctabel中它是-266.64，从而卖出金额 517.28元 （当日净值 1.9400）而不是实际的 517.30元。我为了确认，也改了csv的中2022年3月20日卖出份额分别改成-266.00,-266.66，-266.64等多个值，改成这些值的时候，ctable中的值和csv文件中的卖出份额是一致，但一旦改成-266.65， ctable中的值就-266.64，和cvs文件不一致，是bug吗？

**Comment by refraction-ray** [comment]
> 关于交易数字的一些特别约定，交易数字小数点一位之后的非零位有特别约定，不代表交易的部分。 小数点后第二位如果是5，且当日恰好为对应基金分红日，标志着选择了分红再投入的方式，否则默认分红拿现金。（该默认行为 property 含 2 时可翻转）比如 100.05 的意思是当日分红再投入且又申购了 500 元。

会不会和这个有关系呀，对应日期是分红日吗

**Comment by kaharjan** [comment]
那天不是分红日期，我还发现其他基金的这种份额变化问题，比如csv 文件中的 xx.46 在ctable上变成xx.47 等的问题

**Comment by kaharjan** [comment]
<html>
<body>


2020-11-03 | 6197.94 | -4950.43
-- | -- | --



</body>
</html>  
我在举一下例子：上面的 是002207前海开源金银珠宝混合C 基金的ctable值，在csv文件上的值是-4950.44，我为了确保同一个文件，改了其他值正常变。我最近打印ctable 后发现这个问题，以前我对于0.1份额的差异，主要以为我同一天几次买而计算产生的误差问题，没有仔细分析，现在发现不仅是这个误差问题，还有以上的问题

**Comment by refraction-ray** [comment]
非常感谢你这个发现，有时间我会看一下，初步猜想和电脑二进制表示十进制数可能是有关的，也可能是代码纪录交易数据时有逻辑错误，这个是只和数据有关吗。比如如果记录的是 -4950.44 不管哪个基金或者日期，都会变数字

**Comment by kaharjan** [comment]
我也查看了一下其他基金的*.44份额的数据，有些基金没出现这个问题，目前我发现3-4个基金的这种赎回份额在csv和ctable不一致问题，包括*.44,*.45, *.47 等份额上 。 和上面所说的那样 006229中欧医疗创新股票 的  -266.65 变成-266.64，而 002207前海开源金银珠宝混合C的-4950.44 变成 -4950.43

**Comment by refraction-ray** [comment]
复现该问题

**Comment by refraction-ray** [comment]
66a1f5a1c22a4f5584b73fbbc9edc9f329740c4d 已修复该问题，非常感谢这个发现

**Comment by kaharjan** [comment]
也谢谢你，太好了
