### ISSUE TITLE
期待解锁宏观数据 from ycharts

### ISSUE THREAD

**Issue by freefish1218** [refraction-ray/xalpha#163]
发现在 ycharts.com 上可以获取到宏观数据，比如：

#美国CPI
https://ycharts.com/indicators/us_inflation_rate

#中国PPI
https://ycharts.com/indicators/china_producer_price_index

... ...

抓取方式应该和 ycharts 其他数据抓取类似，期待大佬解锁

**Comment by refraction-ray** [comment]
```
xa.get_daily("yc-indicators/I:USIR")
xa.get_daily("yc-indicators/I:CPPI")
```

0.12 应该可以用了，但是需要去网页找到括号里的代码，暂时未实现根据 [china_producer_price_index]到 I:CPPI 的自动映射，虽然也不难
