### ISSUE TITLE
增量更新分拆信息解析出错

### ISSUE THREAD

**Issue by achjqz** [refraction-ray/xalpha#166]
基金代码：159939
在增量更新时获取到的信息为 

2023-02-15 | 0.5921 | 1.1842 | 1.91% | 场内买入 | 场内卖出 | 每份基金份额分拆2份

`_nfloat` 中解析分拆必须是 x.x 浮点形式
``` python
re.match(r"\D*分拆(\d*\.\d*)\D*", string)
```
是否可以考虑改成小数部分是可选的？
``` python
# 这里使用了非捕获组 (?: ...) 来包含小数部分的匹配项，避免将其作为匹配结果的一部分
re.match(r"\D*分拆(\d*(?:\.\d*)?)\D*", string)
```
其他类型如分红，拆分等是否也有此问题？

**Comment by refraction-ray** [comment]
c7b6153f34c9561bbe4133f878326ea11d080a6e 修复
