### ISSUE TITLE
数据错误。

### ISSUE THREAD

**Issue by tianlinzx** [refraction-ray/xalpha#179]
Fails at fetching url: https://cn.investing.com/indices/germany-30. Try again.
Fails at fetching url: https://cn.investing.com/indices/germany-30. Try again.
Fails at fetching url: https://cn.investing.com/indices/germany-30. Try again.
Fails at fetching url: https://cn.investing.com/indices/germany-30. Try again.
Fails at fetching url: https://cn.investing.com/indices/germany-30. Try again.
Still wrong at fetching url: https://cn.investing.com/indices/germany-30. after 5 tries.

**Comment by refraction-ray** [comment]
duplicate with https://github.com/refraction-ray/xalpha/issues/118
