### ISSUE TITLE
基金持仓资产比例

### ISSUE THREAD

**Issue by aaronyunzhao** [refraction-ray/xalpha#18]
了解到get_fund_holdings()可以得到一只基金的stock, bond持仓列表（头部？），对于大致的资产组合分析很有用。我的问题是，能否得到一只基金的stock, bond, money, others的持仓比例？不知是不是我没找到用法，请指教，谢谢。

**Comment by refraction-ray** [comment]
get_fund_holdings 对于 2，4季度应该可以拿到全部的股票持仓，债券持仓总是只能拿前5，这是和基金半年报年报的披露要求相关的。年报必须披露全部股票持仓但只需披露前五的债券类持仓。

持仓中股票，基金，债券的比例也是要披露的，现成的数据在天天基金的这里：http://fundf10.eastmoney.com/zcpz_100032.html。 这个功能 xalpha 暂时还没有接口，以后可以考虑添加。

**Comment by aaronyunzhao** [comment]
了解了，谢谢！

**Comment by refraction-ray** [comment]
基金持仓的现金债券股票的比例，现在可以通过 ``xa.get_daily("pt-F100032")`` 来获取。github 版本已经有了，pip 版本可能还得之后发布。

**Comment by aaronyunzhao** [comment]
> 基金持仓的现金债券股票的比例，现在可以通过 `xa.get_daily("pt-F100032")` 来获取。github 版本已经有了，pip 版本可能还得之后发布。

赞，谢谢！功能越来越完善。
