### ISSUE TITLE
indexinfo报错

### ISSUE THREAD

**Issue by tianlinzx** [refraction-ray/xalpha#180]
IndexError                                Traceback (most recent call last)
Cell In[4], line 2
      1 # 再选取中证500指数本身和普通500指数基金做比较
----> 2 zz500 = xa.indexinfo("0000905")
      3 guangfa = xa.fundinfo("162711")

File [~/github/xalpha/doc/samples/../../xalpha/info.py:1213](https://file+.vscode-resource.vscode-cdn.net/Users/calvin/github/xalpha/doc/samples/~/github/xalpha/xalpha/info.py:1213), in indexinfo.__init__(self, code, value_label, fetch, save, path, form)
   1205 self.rate = 0
   1206 self._url = (
   1207     "http://quotes.money.163.com/service/chddata.html?code="
   1208     + code
   (...)
   1211     + "&fields=TCLOSE"
   1212 )
-> 1213 super().__init__(
   1214     code, value_label=value_label, fetch=fetch, save=save, path=path, form=form
   1215 )

File [~/github/xalpha/doc/samples/../../xalpha/info.py:342](https://file+.vscode-resource.vscode-cdn.net/Users/calvin/github/xalpha/doc/samples/~/github/xalpha/xalpha/info.py:342), in basicinfo.__init__(self, code, fetch, save, path, form, round_label, dividend_label, value_label)
    340 self.format = form
    341 if fetch is False:
--> 342     self._basic_init()  # update self. name rate and price table
    343 else:

**Comment by refraction-ray** [comment]
duplicate with https://github.com/refraction-ray/xalpha/issues/169
