### ISSUE TITLE
get_daily中使用雪球源的股票数据，返回200，但内容为空，浏览器获取则url则正常

### ISSUE THREAD

**Issue by Chenyang-Lu** [refraction-ray/xalpha#185]
如题，不知是雪球偶尔故障，还是雪球开始屏蔽python requests了
雪球返回json数据：
{'data': {'items': [], 'items_size': 0}, 'error_code': 0, 'error_description': ''}
url在浏览器里正常：
![image](https://github.com/refraction-ray/xalpha/assets/28410250/fb874fb4-62be-4c8a-b83e-e6026437e8ab)

**Comment by cqzhao** [comment]
嗯，昨天同样遇到这个问题

**Comment by cqzhao** [comment]
找到原因了，在cookies中需要增加一个"u"即可。
` r = rget_json(
        url.format(
            code=code, tomorrow=int(tomorrow_ts() * 1000), count=count, type_=type_
        ),
        cookies={"xq_a_token": get_token()[0],"u":get_token()[1]},
        headers={"user-agent": "Mozilla/5.0"},
    )`
get_token()函数修改如下
`def get_token():
    """
    获取雪球的验权 token，匿名也可获取，而且似乎永远恒定(大时间范围内会改变)

    :return:
    """
    r = rget("https://xueqiu.com", headers={"user-agent": "Mozilla"})
    return r.cookies["xq_a_token"],r.cookies["u"]`

**Comment by refraction-ray** [comment]
@cqzhao , 欢迎 PR 修复

**Comment by cqzhao** [comment]
我还修改了其他的东西，有点乱，能pr吗？

**Comment by refraction-ray** [comment]
@cqzhao , 其他东西具体是指？如果是必要修复也可以一起。如果是个人的定制化需求，最好和修复的部分分开，当然你可以说明其他修改的必要性，我也很乐意 review

**Comment by Chenyang-Lu** [comment]
感谢！已解决 @cqzhao

**Comment by pang123hui** [comment]
![image](https://github.com/user-attachments/assets/7c97424e-6541-4d14-b753-ea16d073b352)

非常感谢，修改后已经可以拿到数据，但是相比之前，港股都变成了英文缩写，看着不是很习惯

**Comment by refraction-ray** [comment]
should be fixed by 9140c9b217427544c27b83b20114fa3e343ace21
