### ISSUE TITLE
关于标普官网数据源

### ISSUE THREAD

**Issue by Astraeux** [refraction-ray/xalpha#19]
目前代码pytest执行报错：ValueError: Must explicitly set engine if not passing in buffer or path for io.
``` 
#464行
    r = rget(
        url,
        headers={
            "sec-fetch-dest": "document",
            "sec-fetch-mode": "navigate",
            "sec-fetch-site": "none",
            "sec-fetch-user": "?1",
        },
    )
    df = pd.read_excel(r.content)
```

最后一行改成 df = pd.read_excel(url) 可以通过测试，但这样就没法传递header了

**Comment by refraction-ray** [comment]
你是说现在 tests 里对应的例子都会报错吗。会不会是 pandas 版本的问题？我的pd 是1.0.1.
或者是网络问题，标普官网网络连接也可能不太稳定。这里尽量还是网络获取部分用 rget，因为 rget 还控制了代理和日志，最好全通过 rget 走网络连接。

**Comment by Astraeux** [comment]
嗯，升级pandas就好了，之前安装joinquant sdk限制了pandas版本低于0.25.3
