### ISSUE TITLE
关于volatility算法

### ISSUE THREAD

**Issue by molartech** [refraction-ray/xalpha#20]
```
    def volatility(price, date=yesterdayobj()):
        df = pd.DataFrame(data={"rate": indicator.ratedaily(price, date)})
        return df.std().rate * 15.8144
```

```
    def ratedaily(price, date=yesterdayobj()):
        partp = price[price["date"] <= date]
        return [
            (partp.iloc[i + 1].netvalue - partp.iloc[i].netvalue)
            / partp.iloc[i].netvalue
            for i in range(len(partp) - 1)
        ]
```

ratedaily用了过去所有天数的采样，而volatility用了15.8144（252交易日方差）参数，是不是不太合适？

ratedaily这里的计算只用采样252个即可？

**Comment by refraction-ray** [comment]
这个应该是我好久之前写的了。首先，现在看来我这里实现的很烂，现在看用 pandas 自带的 difference 可以又快又好，不需要脱离 DataFrame 或者写循环。

其次这个波动性的定义现在看来也不一定好。（有些量化指的波动性是每日涨幅对数值的标准差）

如果不考虑定义的分歧和实现很烂的话，这里的正确性好像是没问题的。 price 这个 DataFrame 实际上只包括交易日的，你也可以打印出来检查一下，也就是说 price["date"] 并不包括周末之类的，那么每年大概250天左右。

**Comment by refraction-ray** [comment]
Marked as solved as the post is stale, feel free to reopen it if you have any further question
