### ISSUE TITLE
关于最新版本的安装和测试

### ISSUE THREAD

**Issue by kuangtu** [refraction-ray/xalpha#21]
我clone 代码之后，universal.py增加了一个源。
（1）通过python setup.py install测试最新版本使报错,
![image](https://user-images.githubusercontent.com/3457291/80392731-1e444b00-88e2-11ea-86d9-87d0a07d83c5.png)
感觉是编码的问题。我的是windows环境+python3.7
（2）通过cd tests/ && pytest 也报错。
![image](https://user-images.githubusercontent.com/3457291/80393007-78451080-88e2-11ea-834a-45676ccab6a8.png)
我的pytest版本是5.1.3是不是版本的问题？
谢谢！

**Comment by refraction-ray** [comment]
关于（1），好像 windows terminal 默认编码是 gbk，以前也有人和我反应过这个，不过我手头没 windows 测试，应该把 setup.py 的第五行改成 ``with open("README.md", "r", encoding="utf-8") as fh:`` 就可以安装了。
关于 （2），我 pytest 3，4，5都有测试，没能复现，是只有 ``test_get_ycharts`` 会报错吗，你可以先实验下 ``pytest test_i.py`` 及其他测试文件，看看是都有问题，还是某个测试函数会报错

**Comment by kuangtu** [comment]
（1）修改了可以了；
（2）全部。应该是pytest相关的库版本问题，做了更新。
（3）我在README.md里面做了说明。

**Comment by refraction-ray** [comment]
> （3）我在README.md里面做了说明。

encoding=“utf-8” 直接加到 setup.py 的代码里也行，应该不影响其他系统。
