### ISSUE TITLE
请问怎么获得前复权的价格？

### ISSUE THREAD

**Issue by leejiajun** [refraction-ray/xalpha#23]
我用的是这个函数，xalpha.universal.get_daily()

**Comment by refraction-ray** [comment]
这个默认应该就是前复权的数据，还是您遇到了明显不符合的数据？我倒是可以考虑之后增加不复权和后复权的数据，现在A股日线数据来源都是雪球，如果雪球数据源有误的话，这里也会有问题。但我其实不太清楚雪球数据质量究竟如何，因为我本人做个股分析不多。

**Comment by leejiajun** [comment]
感谢
