### ISSUE TITLE
pip install 时报错找不到 beatifulsoup4  4.9.0

### ISSUE THREAD

**Issue by rogue117** [refraction-ray/xalpha#24]
Collecting beautifulsoup4>=4.9.0 (from xalpha)
  Could not find a version that satisfies the requirement beautifulsoup4>=4.9.0 (from xalpha) (from versions: )
No matching distribution found for beautifulsoup4>=4.9.0 (from xalpha)

**Comment by refraction-ray** [comment]
这个比较奇怪，我能想到的几个原因。
pip 用的源不是官方源，而是为了速度快用了国内的一些镜像源，这些镜像源可能更新不及时。
pip 是 python2 带的 pip。
网络连接方面的问题。
建议你直接试下 ``pip3 install beautifulsoup4==4.9.0``, 看看会不会报错

**Comment by refraction-ray** [comment]
closed since the post is staled. Feel free to ping me if this issue is still relevant
