### ISSUE TITLE
基金投资模拟回测简明教程（以一揽子主动基组合回测为例）：sys=xa.mul(status=df) # 获取模拟交易组合 报错！

### ISSUE THREAD

**Issue by wyjbird** [refraction-ray/xalpha#25]
报错提示：ParserFailure: Unrecognized fund, please check fund code you input.

**Comment by refraction-ray** [comment]
这个应该是 xalpha 的最新版本还没发布的缘故，报错的原因在于 df 那个手动生成的账单里，**date 不在 DataFrame 第一列**。这个 github 最新的 xalpha 已经支持了，但 pip 的发布版还没支持。现阶段可以手动把 data 调到 df 的第一列即可正常运行。

**Comment by refraction-ray** [comment]
最新的 pip 版本应该已修复该问题
