### ISSUE TITLE
是否可以抓取台灣上市的ETF跟基金資料？

### ISSUE THREAD

**Issue by boyac** [refraction-ray/xalpha#26]
Hi Ray,
xalpha 是否可以抓取台灣上市的ETF跟基金資料？

Thanks

**Comment by refraction-ray** [comment]
Hi, 我不知道你哪种语言更习惯，我就先用中文回复了。
xalpha 可以抓取的数据，除了 A 股，港股和美股市场的数据有额外单独的数据源之外，其他数据是否存在取决于 xalpha 支持的数据源中有没有相应的标的。 xalpha 现在支持所有可以在 investing.com, ft.com, bloomberg.com, finance.yahoo.com, ycharts.com 上面可以找得到的标的。所有支持的数据源及标的代码格式，可以参考[文档](https://xalpha.readthedocs.io/en/latest/xalpha.html#xalpha.universal.get_daily)。
如果台湾相应的 ETF 和基金在这些网站可以找到对应的页面，那么抓取**每日价格数据**是没问题的。部分数据源也支持一定的实时数据和简单的元信息。
当然这些基金诸如分红，拆合股以及份额之类的元信息暂时不支持，这种细节只有大陆的基金支持的比较完善。

**Comment by boyac** [comment]
thanks a million! 我再來試試🙏
