### ISSUE TITLE
以008969为例，trade函数执行会一直卡死

### ISSUE THREAD

**Issue by wyjbird** [refraction-ray/xalpha#27]
示例代码：  for i in range(len(new_founds)):  #我想从基金池挑选一个收益率高的
            try:
                found = new_founds[i]['code']
                jshs = xa.fundinfo(found)
                bah = xa.policy.buyandhold(jshs, start='2019-01-01', totmoney=100000)
                # 简单的一次性买入类，从 start 日买入后就一直持有，始终选择分红再投入
                bah.sellout('2020-05-12') # 选定日期全部卖出
                print(bah.status)
                jshstrade = xa.trade(jshs, bah.status) # 尝试交易一下   008969基金（封闭期）卡死
                xxrate = str(jshstrade.xirrrate())

                spamwriter.writerow({found, xxrate})
                print(found + "成功" ,end="   ")
            except Exception as e:
                print(e)

**Comment by refraction-ray** [comment]
Nice catch!
我可以复现你的问题:
```python
jshs = xa.fundinfo("008969")
bah = xa.policy.buyandhold(jshs, start='2019-01-01', totmoney=100000)
bah.sellout('2020-05-12') # 选定日期全部卖出
# print(bah.status)
jshstrade = xa.trade(jshs, bah.status)
```
问题的根源在于这种基金的特殊性，净值每周只有一个数字。我会尽快完善 trade 的处理逻辑，完善后这种基金依旧是可以处理的。其他正常的每日更新净值的基金都没有问题。

**Comment by refraction-ray** [comment]
https://github.com/refraction-ray/xalpha/commit/df5afc4670b63e00dc7622799e9f486380e7c15b
应该已经修复了该问题，我将最近更新到 pip 上去，现在 github 版本应该已经正常了。
