### ISSUE TITLE
请问获取bloomberg数据有没有办法降低封禁机率？

### ISSUE THREAD

**Issue by Astraeux** [refraction-ray/xalpha#28]
现程序获取"BB-FLDIVBK:FP"、"BB-FGERBIU:ID"等bloomberg数据时非常容易被封禁IP，需人工解封

有没有办法降低封禁机率？或者替换为其它数据源？

**Comment by refraction-ray** [comment]
一般来讲 bloomberg 的数据都可以在 ft.com 上找到，你这两个可能分别是 "FT-FR0011346394:CHF"， "FT-IE00B3PPHH68:USD"。还有就是如果是做 QDII 净值预测的话，每日只需要获取这些标的一次，理论上不太至于被 ban ip。

**Comment by Astraeux** [comment]
谢谢，目前看还是换成用ft.com比较合适，限制每日只获取一次bloomberg比较复杂，因为获取过程中可能失败需要重试

**Comment by Astraeux** [comment]
BB-GUIGLGI:LX 我搜了很久都没在 ft.com 上找到，能帮忙看下吗？

**Comment by refraction-ray** [comment]
> BB-GUIGLGI:LX 我搜了很久都没在 ft.com 上找到，能帮忙看下吗？

应该是这个： FT-LU0345780281:USD。虽然单价不一样，但是是一个

```python
xa.Compare("BB-GUIGLGI:LX", "FT-LU0345780281:USD").v()
```

**Comment by refraction-ray** [comment]
closed for now, feel free to reopen if you have further issues on codes in these websites

**Comment by Astraeux** [comment]
> > BB-GUIGLGI:LX 我搜了很久都没在 ft.com 上找到，能帮忙看下吗？
> 
> 应该是这个： FT-LU0345780281:USD。虽然单价不一样，但是是一个
> 
> ```python
> xa.Compare("BB-GUIGLGI:LX", "FT-LU0345780281:USD").v()
> ```

BB-GUIGLGI:LX 对应的好像是：FT-LU0345780521:usd
