### ISSUE TITLE
关于sysfix.v_netvalue()的开始时间

### ISSUE THREAD

**Issue by wyjbird** [refraction-ray/xalpha#31]
在https://nbviewer.jupyter.org/github/refraction-ray/xalpha/blob/master/doc/samples/virtualtrade.ipynb案例中，我注意到out23中的开始时间是2019-05-06，但上面代码为sysfix.bcmkset(xa.vinfo("SH000300"), start="2017-01-01") # 设定比较基准为沪深300，我想问一下2019-05-06是怎么得来的？为什么不是从2017-01-01开始？

**Comment by refraction-ray** [comment]
好问题。
这个应该是这句的问题：
```
sysfix.bcmkset(xa.vinfo("SH000300"), start="2017-01-01")
```
1. vinfo 是比 indexinfo 更灵活的类，这里需要在 vinfo 里也指定 start，不然默认是一年数据，也就是可以改成 
```
sysfix.bcmkset(xa.vinfo("SH000300", start="2017-01-01"), start="2017-01-01")
```
2. 或者直接改成 indexinfo 也是可以的，这个默认拉取全部可用数据
```
sysfix.bcmkset(xa.indexinfo("SH000300"), start="2017-01-01")
```

我这边应该就是随手写的，没注意这点。如果只是用沪深常见的指数比较，还是推荐直接用 indexinfo, vinfo 很灵活但是麻烦些。

**Comment by refraction-ray** [comment]
41675931f70ec511aa16c00b417c7f589c86af3b 已修复该示例的时间起点问题
