### ISSUE TITLE
请问在自定义policy的时候有没有一个虚拟的account类来统计账户下当前收益、持仓情况等信息？

### ISSUE THREAD

**Issue by MyCodeBattle** [refraction-ray/xalpha#37]
因为策略需要用到盈利，不知道是需要自己维护还是有现成的工具？找了好久没找到，求指导

**Comment by refraction-ray** [comment]
如果我理解的对的话，你是希望自定义 policy 类相应策略的时候用的不仅是和投资标的有关的数据，还希望用到利用该 policy 的对应账户当时的持仓量和利润之类的数据对吧？如果是这样的话，目前这个简单的 policy 类还不方便，没有现成的 API 拿到持仓相关的动态数据。
因为现在的版本 policy 是静态生成完整的投资账单，然后交易类去处理分析的。你说的功能属于动态的回测引擎，而非静态的，这也是我一直想加的功能。现在的话，自己非要实现也不是做不到（反正就是最后生成账单而已），只不过效率不高，或者比较拧巴。

**Comment by refraction-ray** [comment]
最新的0.10.0版本，引入了 xa.backtest 模块做这种动态回测，现在还没什么文档，但是代码本身有一些具体例子的实现，你如果感兴趣可以参考一下 https://github.com/refraction-ray/xalpha/blob/master/xalpha/backtest.py。

基本上就是自己自定义一个策略类

```python
class MyPolicy(xa.backtest.BTE):
    def prepare(self):
    
    def run(self, date):
```

然后可以
```python
p = MyPolicy(....)
p.backtest()
sys = p.get_current_mul()
```
拿到 sys 之后就和普通基金组合的分析一样了

**Comment by MyCodeBattle** [comment]
> 最新的0.10.0版本，引入了 xa.backtest 模块做这种动态回测，现在还没什么文档，但是代码本身有一些具体例子的实现，你如果感兴趣可以参考一下 [https://github.com/refraction-ray/xalpha/blob/master/xalpha/backtest.py。](https://github.com/refraction-ray/xalpha/blob/master/xalpha/backtest.py%E3%80%82)
> 
> 基本上就是自己自定义一个策略类
> 
> ```python
> class MyPolicy(xa.backtest.BTE):
>     def prepare(self):
>     
>     def run(self, date):
> ```
> 
> 然后可以
> 
> ```python
> p = MyPolicy(....)
> p.backtest()
> sys = p.get_current_mul()
> ```
> 
> 拿到 sys 之后就和普通基金组合的分析一样了

谢谢！我研究一下！
