### ISSUE TITLE
调用xirrrate的时候出现RuntimeError: Failed to converge after 50 iterations问题

### ISSUE THREAD

**Issue by MyCodeBattle** [refraction-ray/xalpha#41]
使用的csv如下：
```
date,163406
20200305,4071
```

```
import xalpha as xa

fund = xa.fundinfo('163406')
rec = xa.record('status.csv')
tra = xa.trade(fund, rec.status)

print(tra.xirrrate('2020/4/2'))
```
抛出了RuntimeError: Failed to converge after 50 iterations, value is (-1.2962216991414534e+86+1.3656316902725554e+85j).异常，请问是什么原因引起的？应该如何解决？

**Comment by refraction-ray** [comment]
时间太短，下跌太猛，所以算不出来年化。如果是大程序里的一部分
```python
try:
    t.xirrrate()
except RuntimeError:
    pass
```
避免报错就好了。
还有就是调整年化初始的猜测值 ``tra.xirrrate("2020-04-02", guess=-0.9)`` 好像就不报错了。

**Comment by MyCodeBattle** [comment]
> 时间太短，下跌太猛，所以算不出来年化。如果是大程序里的一部分
> 
> ```python
> try:
>     t.xirrrate()
> except RuntimeError:
>     pass
> ```
> 
> 避免报错就好了。
> 还有就是调整年化初始的猜测值 `tra.xirrrate("2020-04-02", guess=-0.9)` 好像就不报错了。

原来如此， 谢谢！
