### ISSUE TITLE
本次报错 以前没事：sysfix.summary(myenddate) 方法执行后报错 （初始金额写>0即可 不知道为啥）

### ISSUE THREAD

**Issue by wyjbird** [refraction-ray/xalpha#43]
virtualtrade.py  开始时间：20200707（或者7月后任意一天）  结束时间：20200710  执行后报错除数等于0  ；如果把开始时间调成6月或者更早，就没事； 我试了一些基金代码和金额，好像与他们无关。

代码片段如下：
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-10-e881366ef4ea> in <module>
----> 1 sysfix.summary(myenddate)
      2 # 我们看到此时出现了货币基金选项，这是因为默认现金分红会智能处理帮你买入货币基金

c:\users\asus\appdata\local\programs\python\python38\lib\site-packages\xalpha\multiple.py in combsummary(self, date)
    169         for fund in self.fundtradeobj:
    170             summarydf = summarydf.append(
--> 171                 fund.dailyreport(date), ignore_index=True, sort=True
    172             )
    173         tname = "总计"

c:\users\asus\appdata\local\programs\python\python38\lib\site-packages\xalpha\trade.py in dailyreport(self, date)
    547         currentcash = myround(currentshare * value)
    548         btnk = bottleneck(partcftb)
--> 549         turnover = turnoverrate(partcftb, date)
    550         ereturn = myround(currentcash + totoutput - totinput)
    551         if currentshare == 0:

c:\users\asus\appdata\local\programs\python\python38\lib\site-packages\xalpha\trade.py in turnoverrate(cftable, end)
     93     start = cftable.iloc[0].date
     94     tradeamount = sum(abs(cftable.loc[:, "cash"]))
---> 95     turnover = tradeamount / bottleneck(cftable) / 2.0
     96     if (end - start).days <= 0:
     97         return 0

ZeroDivisionError: float division by zero

**Comment by refraction-ray** [comment]
可以贴一下能够复现错误的完整代码吗
