### ISSUE TITLE
重复执行get_daily 出错，另外df格式使engine对表的大小写敏感

### ISSUE THREAD

**Issue by ATouge** [refraction-ray/xalpha#46]
# 获取基金数据
xa.get_daily("f501018", prev=5)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
f:\python3.8\lib\site-packages\xalpha\universal.py in wrapper(*args, **kws)
   1834                             if has_weekday(nextday_str, kws["end"]):  # 新更新的日期里有工作日
-> 1835                                 df2 = f(*args, **kws)
   1836                                 if df2 is not None and len(df2) > 0:

f:\python3.8\lib\site-packages\xalpha\universal.py in _get_daily(code, start, end, prev, _from, wrapper, handler, **kws)
   1039 
-> 1040         df = get_historical_fromxq(code, count, type_=type_)
   1041         df = prettify(df)

f:\python3.8\lib\site-packages\xalpha\universal.py in get_historical_fromxq(code, count, type_, full)
    167     )
--> 168     df = pd.DataFrame(data=r["data"]["item"], columns=r["data"]["column"])
    169     df["date"] = (df["timestamp"]).apply(ts2pdts)  # reset hours to zero

KeyError: 'item'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-20-855178c2614d> in <module>
      1 # 获取基金数据
----> 2 xa.get_daily("f501018", prev=5)

f:\python3.8\lib\site-packages\xalpha\universal.py in wrapper(*args, **kws)
   1861                                 ).strftime("%Y%m%d")
   1862                         is_changed = True
-> 1863                         df0 = f(*args, **kws)
   1864 
   1865                 if df0 is not None and len(df0) > 0 and is_changed:

f:\python3.8\lib\site-packages\xalpha\universal.py in _get_daily(code, start, end, prev, _from, wrapper, handler, **kws)
   1038         code, type_ = decouple_code(code)
   1039 
-> 1040         df = get_historical_fromxq(code, count, type_=type_)
   1041         df = prettify(df)
   1042     elif _from in ["zhongjianjia", "zjj", "chinamoney", "ZJJ"]:

f:\python3.8\lib\site-packages\xalpha\universal.py in get_historical_fromxq(code, count, type_, full)
    166         headers={"user-agent": "Mozilla/5.0"},
    167     )
--> 168     df = pd.DataFrame(data=r["data"]["item"], columns=r["data"]["column"])
    169     df["date"] = (df["timestamp"]).apply(ts2pdts)  # reset hours to zero
    170     return df

KeyError: 'item'

**Comment by refraction-ray** [comment]
这个报错似乎是因为代码格式问题，应该是 ``xa.get_daily("F501018")``，至于对应的代码格式和表名的转化可以参考这个issue： https://github.com/refraction-ray/xalpha/issues/38#issuecomment-652919086

**Comment by ATouge** [comment]
谢谢大佬，当第一遍执行xa.get_daily("F501018")可以正常，再次执行时，会报错，没有这张表，当指定key时，正常。谢谢

**Comment by refraction-ray** [comment]
那就是和我上面提到的issue 完全相同的问题，由于数据库引擎大小写不敏感 引起的，解决方案也都在那个 issue 了，最推荐的方法是 ``xa.set_backend(backend="sql", path=engine, key_func=lambda s:s.lower())``, 一劳永逸，不需要操心 key 了

**Comment by ATouge** [comment]
谢谢 大佬，非常感谢
