### ISSUE TITLE
请问我怎么清除xaplph 缓存，我模拟记录了基金数据，期间出错过一次，再次运行代码时，已经记录我购买了两倍的

### ISSUE THREAD

**Issue by ATouge** [refraction-ray/xalpha#47]
![image](https://user-images.githubusercontent.com/24560507/89508434-81f2e400-d800-11ea-8886-362d6b42cddd.png)
![image](https://user-images.githubusercontent.com/24560507/89508493-92a35a00-d800-11ea-9afb-933a7fd75e45.png)

**Comment by refraction-ray** [comment]
不太清楚是什么意思，看上面的表格，并不是两倍重复的，而是 110017 和 110011 两个基金都有申购记录了。如果有不需要的，pandas 删除对应列即可 df.drop("110011")

**Comment by ATouge** [comment]
我也不太清楚，按道理讲我不应有有这3只基金的申购记录才对，但是执行下来就会出现购买2000的情况，我调整两个为1500时，就变成了这个样子，我大概可以猜出来原因了，我将申购日期调整为前一日，就正常了，大概是因为我填写的申购日期是当天，但是当天的基金净值还没有出来，所以出现了错误结果。

**Comment by ATouge** [comment]
我也不太清楚，按道理讲我不应有有这3只基金的申购记录才对，但是执行下来就会出现购买2000的情况，我调整两个为1500时，结果申购了3000。我将申购日期调整为前一日，就正常了，我大概可以猜出来原因了，大概是因为我填写的申购日期是当天，但是当天的基金净值还没有出来，所以出现了错误结果。

**Comment by refraction-ray** [comment]
我懂你的意思了，这里交易引擎处理确实有点问题。今日的申购，由于未出净值，默认按昨日申购处理这是默认行为，但是这边重复记录确实是 bug，我会进行修复

**Comment by ATouge** [comment]
谢谢大佬，大佬注意身体，哈哈哈

**Comment by refraction-ray** [comment]
0.10.1 应该已经修复了重复购买的问题
