### ISSUE TITLE
xa.policy.buyandhold加入end日期参数在v_totvalue时没起作用

### ISSUE THREAD

**Issue by leeleilei** [refraction-ray/xalpha#48]
```python
import pandas as pd

fgth = xa.fundinfo('161005')

# 截取三个时间段的数据
st1 = xa.policy.buyandhold(fgth, start='2005-01-01', end='2006-08-01').status
st2 = xa.policy.buyandhold(fgth, start='2009-03-01', end='2014-08-01').status
st3 = xa.policy.buyandhold(fgth, start='2016-03').status

st = pd.concat([st1, st2, st3])
fgth_t = xa.trade(fgth, st)
fgth_t.v_totvalue()
```

图示中仍然保留着跳过的时间段数据
![image](https://user-images.githubusercontent.com/538984/89705134-2efa6780-d98d-11ea-8e08-789864f9ad9c.png)

单独取一个st作图，也是类似现象。

**Comment by refraction-ray** [comment]
``buyandhold`` 不支持卖出，函数名就是买入并持有，你可以这样手动卖出
```python
fgth = xa.fundinfo('161005')

st1 = xa.policy.buyandhold(fgth, start='2005-01-01', end='2006-08-01')
st1.sellout(date="20060202")

fgth_t = xa.trade(fgth, st1.status)
```

**Comment by leeleilei** [comment]
嗯，可以。
buyandhold这里的end参数还有其他用途吗？

**Comment by refraction-ray** [comment]
> buyandhold这里的end参数还有其他用途吗？

这个是一般 policy 通用默认的一个参数，指的是会在 start 到 end 之间跑相应的策略，只不过对于 buyandhold 没什么意义，因为只在 start 那天买入（但还是有点区别，end 之后的日期里，分红会变成现金分红，而 start 到 end 之间的时段，分红是分红再投入）。
如果需要比较精细的控制策略的话，可以考虑从头完全手动生成记账单，这样可以避免各个特定策略可能的细节问题。

或者我现在实现了一个更灵活的回测框架模块，https://github.com/refraction-ray/xalpha/blob/master/xalpha/backtest.py，
一些使用事例在 https://github.com/refraction-ray/xalpha/blob/master/tests/test_backtest.py
