### ISSUE TITLE
场外基金实时情况能获取吗？

### ISSUE THREAD

**Issue by kaharjan** [refraction-ray/xalpha#50]
我用了一下 xa.get_rt() 函数，这函数不能得到场外基金的实时情况。
发生了一下错误：

-> 1166     n = r["data"]["quote"]["name"]
   1167     q = r["data"]["quote"]["current"]

TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

IndexError                                Traceback (most recent call last)
<ipython-input-26-70515bc9d8fd> in <module>
      1 # xa.get_t0("005224")
      2 # xa.get_daily("005224")
----> 3 xa.get_rt("005224")

~/anaconda3/envs/py3.6/lib/python3.6/site-packages/xalpha-0.10.0-py3.6.egg/xalpha/universal.py in get_rt(code, _from, double_check, double_check_threhold, handler)
   1589                 "Fails due to %s, now trying backup data source from sina" % e.args[0]
   1590             )
-> 1591             return get_rt_from_sina(code)
   1592     elif _from in ["sina", "sn", "xinlang"]:
   1593         try:

~/anaconda3/envs/py3.6/lib/python3.6/site-packages/xalpha-0.10.0-py3.6.egg/xalpha/universal.py in get_rt_from_sina(code)
   1332     else:
   1333         d["currency"] = "USD"
-> 1334         d["current"] = float(l[1])
   1335         d["percent"] = float(l[2])
   1336         d["current_ext"] = _float(l[21]) if _float(l[21]) > 0 else None

IndexError: list index out of range

**Comment by refraction-ray** [comment]
各种标的代码都有具体的格式，场外基金代码前要加 F

**Comment by kaharjan** [comment]
哦，明白了，加F以后可以了，谢谢！！！
