### ISSUE TITLE
一些小建议

### ISSUE THREAD

**Issue by laigen** [refraction-ray/xalpha#52]
设计接口中用到的 symbol ， 尽量贴近 bloomberg 或者 WIND ， 这样使用者会方便一些

有些数据的爬取，可以考虑依赖于 akshare 这类开源项目，在这类基础上封装缓存。

**Comment by refraction-ray** [comment]
现在 symbol 的设计基本上是跟数据源走的，如果可以在某个数据源网站找到需要的标的，那么通过对应网址就能自然得出其在 xalpha 调用的 symbol。bloomberg 的名称的话，通过 BB-* 调用就可以获取到。当然由于我尝试把各种数据都塞进了 ``get_daily`` 的接口，有些 symbol 的规定会变得比较奇怪。
全部使用某一个现成系统的标的名称，有几个问题，1 是即使 WIND 或者 bloomberg，我想可能数据覆盖也不全，那么有些标的，还得自己再定名称。2 是内部处理会比较难办，比如如果都使用 bloomberg 的 symbol 规定，那么想要走 ft.com 数据源的时候，很难通过代码把 bloomberg 的 symbol 翻译成 ft.com  的网址。

调用其他开源库的数据接口，我到也不排斥，现在没有主要基于的考虑是： 1. 暂时 xalpha 这些数据直接爬虫获取都比较容易，同时走了统一的 xalpha 内部封装的下载接口，可以设置代理和日志，管理统一些 2. 还是想整个库“薄”一些，尽量只依赖一些最基础也最靠谱的上游，毕竟有些开发者很喜欢做 breaking change，下游开发者就会比较难受。当然如果将来有一些数据自己写爬虫比较麻烦的话，引入第三方的这类数据爬取库，我也没意见 （当然最好还是直接将对应库里相应的爬取代码复制过来）

如果是用户现在就希望调用一些其他开源库提供的数据，但是又想同时内嵌在 xalpha  ``get_daily`` 这种具有透明缓存的统一接口里，其实现在也有方案实现，可以参考 https://xalpha.readthedocs.io/en/latest/advance.html#get。

**Comment by laigen** [comment]
1) 不同的数据源一般都有一套自己的 symbol 映射规则，因为 get_daily() 的接口是统一的，并且设计目标是跟底层的源隔离，所以从长远角度考虑，一定是背靠某种大佬的定义方式，这样才能降低API学习的成本。一开始可以支持有限的证券种类，底层写若干个 rule based mapping function 去映射不同 target website 用到的代码。

2) 不要低估wind或 bloomberg 对于证券标的的覆盖能力。

3) akshare 本身没有db / cache，只是一些网页获取数据的函数接口封装，覆盖的范围比较广。在这个基础上增加 data cache 或者 data cleaning 的功能，可以让精力更多的集中于上层的分析功能。并且这个库的 star 数比较高，一旦网页发生变动，后期的维护成本是很高的。"借力" 的好处在于后期的维护上。

4) 额外的小建议，有关时间序列数据的存储，可以看一下 project 叫 arctic ， 是一个美国蛮有名的金融机构开源出来的项目。用 mysql 最大的问题在于，如果要将较多的时间序列数据加载到 dataframe 时，性能很差。

**Comment by refraction-ray** [comment]
非常感谢你的建议，下面是我的一些想法

1. get_daily 接口很难做到和数据源无关，正如你说的 
> 不同的数据源一般都有一套自己的 symbol 映射规则

这套规则往往过于复杂，也不见得有规律，比如 investing.com 的 url 和 ft.com url 互相翻译，这种完全就做不到，无法通过硬编码解决。简单说，就是 rule based mapping function 似乎做不到。除非自己去维护一个完整映射包含所有标的的全表，但这个工作量太恐怖了。

或者从另一个角度想，标的 symbol 和数据源（通常是相应网站的 url）耦合，对于用户侧也是比较自然的。很多时候用户是去相应的网站先去查找标的，如果想用 xalpha 分析，那么直接就可以将相应的 url 拿过来改改做 symbol 用。反之，如果标的 symbol 统一到了一套约定，那么用户反而要二次去查在 ft.com 正在看的这个标的，到底在 bloomberg 里叫什么。

2. 现在 get_daily 这个接口包含的东西很多，各种时间序列的数据都可以放进去，比如现在就有每年失业率人口之类的宏观数据，或者各种级别相应久期的企业债平均利率周线数据等等，这些估计一般的金融软件不会有专门的标的名称的，因为其本质上就不是一个金融产品标的。

3. 如果想结合 askshare 的数据接口和 xalpha 这边的缓存等其他功能，从而在 get_daily 直接调用 askshare 的数据，现在也可以用户侧实现，就是我上面回复提供的文档链接。网页变动确实是个大麻烦。不过自己写爬取这块也是好坏都有吧。好的是可以自己马上更新，不需要等待上游更新（可能比较慢从而影响自己使用），坏的是确实很耗费精力。如果你希望把  askshare 现有的接口放进 get_daily 的话，我也没有问题，欢迎贡献。如果你有兴趣，我们可以讨论具体的设计和实现方案。

4. 感谢你的建议，有空我会去看下。不过现在 xalpha 本身性能也很一般，本来可能就应付不了工业级别的金融数据处理，基本上就是个人做一些简单的记账分析和自动化来用的。所以可能瓶颈也不在数据库，python 本身就挺慢的，代码也没什么特别优化。
