### ISSUE TITLE
一个数据常数的意思

### ISSUE THREAD

**Issue by grant36x** [refraction-ray/xalpha#55]
在algorithm_volatility函数的代码里，有乘上一个常数15.8144，看不懂这个数指的是什么意思，起什么作用。是不是可以考虑定义一个常量，然后赋以这个值

def volatility(price, date=yesterdayobj()):
            df = pd.DataFrame(data={"rate": indicator.ratedaily(price, date)})
            return df.std().rate * 15.8144

**Comment by refraction-ray** [comment]
这个来源应该是 $$\sqrt{250}$$，也即一年交易天数的开方。由此可以通过日波动率来计算年波动率。因为波动率是标准差，和数据点数目N的关系是根号N。
