### ISSUE TITLE
麻烦解释一下，这个数据怎么对不上？

### ISSUE THREAD

**Issue by EinsQiang** [refraction-ray/xalpha#56]
非常感谢开发这么好的工具

![image](https://user-images.githubusercontent.com/18229660/92995964-81094c80-f53a-11ea-8b9e-281fffc1be90.png)

fund name: 申万菱信中证500指数优选增强A
fund code: 003986

发现异常的地方，在这里，本身交易中，没有一次卖出，但是交易图上却出现了卖出。

![image](https://user-images.githubusercontent.com/18229660/92996157-ffb2b980-f53b-11ea-99b8-deb78814465e.png)

这个是交易的记录

[003986.csv.zip](https://github.com/refraction-ray/xalpha/files/5212689/003986.csv.zip)

**Comment by refraction-ray** [comment]
这个卖出倒是正常的，因为那周有分红，等效成了卖出。
至于数据异常，似乎是因为提供的账单里有同一日期的超过两笔买入，可以考虑保留合并成一笔，看看数据是否正常

**Comment by EinsQiang** [comment]
好的，非常感谢
