### ISSUE TITLE
用雪球抓取港股和新三板的数据失败

### ISSUE THREAD

**Issue by nehzoug** [refraction-ray/xalpha#57]
我用的版本0.10.0，是不是雪球获取港股和新三板行情的地址换了？

**Comment by refraction-ray** [comment]
港股我这边测试是好的，比如 ``xa.get_daily("HK00700")``。
 新三板的话，我没测试过，也不确定雪球是否有相应的数据（可能没有？）

**Comment by nehzoug** [comment]
不好意思，是我的网络问题导致，不是xalpha的问题

**Comment by nehzoug** [comment]
xalpha没有问题，是我使用的网络问题导致
