### ISSUE TITLE
请问获取基金信息的接口能抓到香港基金吗？就是968开头的，谢谢

### ISSUE THREAD

**Issue by wyjbird** [refraction-ray/xalpha#58]

**Comment by refraction-ray** [comment]
非常好的问题，现在我看好像是不行的，不过天天基金有数据，之后可以增加这个数据的处理，也欢迎其他人做这个的 PR，我觉得这个中港互认基金的数据和交易处理还是很重要的。因为现在可以轻松申购，所以应该有这个需求的人挺多的。

**Comment by wyjbird** [comment]
http://overseas.1234567.com.cn/overseasapi/OpenApiHander.ashx?api=HKFDApi&m=MethodFundList&action=1&pageindex=0&pagesize=9999&dy=1&date1=2019-09-19&date2=2020-09-19&sortfield=W&sorttype=-1&isbuy=0&callback=jQuery1830002481750298088725_1600479642244&_=1600479703137

**Comment by wyjbird** [comment]
http://overseas.1234567.com.cn/overseasapi/OpenApiHander.ashx?api=HKFDApi&m=MethodFundList&action=1&pageindex=0&pagesize=9999&dy=1&date1=2019-09-19&date2=2020-09-19&sortfield=W&sorttype=-1&isbuy=0

**Comment by refraction-ray** [comment]
最新的 github 版本已经实验性支持中港互认基金在 get_rt, get_daily 和 fundinfo 中使用，但由于和国内基金格式的差距，不保证现阶段没有 bug

**Comment by refraction-ray** [comment]
v0.11.0 已添加了对中港互认基金的基本支持，如有功能缺失或 bug 可以再单独开 issue
