### ISSUE TITLE
关于场外基金小数点后.005无法免收购费的问题

### ISSUE THREAD

**Issue by deepopo** [refraction-ray/xalpha#59]
例如申购某场外基金1w元，免收购费，如果输入10000.005，按照文档所说应该是免申购费的，但实际上是依然是默认申购费。但是如果输入10000.0050000001，就视为免申购费了。目前试了几个场外基金都有这样的问题，不知道是不是自己理解错了，如果确实是bug，望修改~

**Comment by refraction-ray** [comment]
感谢反馈，确实有这个问题，没有考虑到计算机二进制造成的数值偏离，将很快修复。神奇的是，我之前测试的时候用的 100.005 就没有问题 ==

**Comment by refraction-ray** [comment]
1af83605f49a0895ae8e2c34d1ff26e260c13884 应该已修复该问题，过些时候会 release 到 pypi

**Comment by deepopo** [comment]
感谢！这个项目真的很棒！

**Comment by refraction-ray** [comment]
v0.11.0 已发布到 pypi
