### ISSUE TITLE
error in tests

### ISSUE THREAD

**Issue by refraction-ray** [refraction-ray/xalpha#6]
`SyntaxError: Unexpected token (LT, '<') at 1:0 between None and LexToken(ID,'html',1,1)`
Seems to be originated from js parser in fundinfo

No essential error is observed in daily use though...

**Comment by refraction-ray** [comment]
now there are some random fails in test_info, the original error vanishes though no source changing...

**Comment by refraction-ray** [comment]
The error in travis is also different from local setup...

**Comment by refraction-ray** [comment]
Now the remaining error is from pandas 1.0+ api break down...

**Comment by sddnuaa** [comment]
测试发现2020年后的数据没法获取，self._url = ( "http://fund.eastmoney.com/pingzhongdata/" + code + ".js" )  # js url api for info of certain fund，是不是由于这边没有返回2020年数据引起的？

**Comment by refraction-ray** [comment]
@sddnuaa , 你用的版本是 pip 安装的版本吗，那个版本有点老，没有 2020 年的工作日数据。
现在 github 的master 是正常的，我最近会把新版本发布到 pypi，到时候 pip 升级一下包就好了。或者你也可以现在先用 github master 的版本

**Comment by sddnuaa** [comment]
直接安装有些问题，但也解决了。
python setup.py install
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    long_description = fh.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 590: illegal multibyte sequence
改成with open("README.md", "r",encoding='utf-8') as fh:解决

FileNotFoundError: [Errno 2] File e:\anaconda3\envs\tf2\lib\site-packages\xalpha-0.1.2-py3.7.egg\xalpha\caldate.csv does not exist: 'e:\\anaconda3\\envs\\tf2\\lib\\site-packages\\xalpha-0.1.2-py3.7.egg\\xalpha\\caldate.csv'
把文件拷贝过去解决

原来用通过pip 清华镜像安装，比较快。这次本地安装，花了好长时间，好在现在能正常使用了 ，谢谢@refraction-ray

**Comment by refraction-ray** [comment]
@sddnuaa ，谢谢提醒，我得记着把 csv 放进 setup.py 需要 include 的 file 里。我这两天就会把新版发布到 pip 上。

**Comment by sddnuaa** [comment]
这个项目相当好，设计也很友好，谢谢分享~ @refraction-ray

**Comment by sddnuaa** [comment]
sysopen.v_tradevolume(bar_category_gap='75%',freq='W') 运行报错，查看代码里发现改成sysopen.v_tradevolume(freq='D') 了，但是运行后没有买入卖出的效果，不知怎么回事？

**Comment by refraction-ray** [comment]
@sddnuaa，支持 pyechart 1.0+ 之后，可视化部分我没什么时间弄，确实改的还不太理想。但我刚才试了下至少 `sys.v_tradevolume(freq='D') ` 和 `sys.v_tradevolume(freq='W') ` 图丑点，但是是有内容的。不知道没有买入卖出的效果具体是指什么。 你可以先检查下，如果用的现在 github 上版本的 xalpha 话，pyecharts 是否是 1.0+ 的版本

**Comment by sddnuaa** [comment]
@refraction-ray 试了一下啊，当导入的csv数据全部是买入的情况，sys.v_tradevolume输出不正常（没有一根根红色的柱子），只有当csv数据中同时有买入卖出的情况，sys.v_tradevolume输出才正常

**Comment by refraction-ray** [comment]
@sddnuaa ,感谢反馈，我复现了你的问题，我看下

**Comment by refraction-ray** [comment]
closed since slimit and ply dependencies are removed
