### ISSUE TITLE
关于收益曲线统计

### ISSUE THREAD

**Issue by pang123hui** [refraction-ray/xalpha#61]
您好，请问下，对于一个xa.mul的记账本，想要绘制一下从一开始到现在的总收益（单位元）曲线，能否有代码可以参考下，非常感谢！

**Comment by refraction-ray** [comment]
```python
date = []
data = []
for d in pd.date_range("2019-01-05", "2020-08-01", freq="W-THU"):
    data.append(sys.summary(d.strftime("%Y-%m-%d")).iloc[0]["基金收益总额"])
    date.append(d)
from pyecharts.charts import Line
line=Line()
line.add_xaxis(xaxis_data=date)
line.add_yaxis(series_name="总收益",y_axis=data, is_symbol_show=False)
line.render("test.html")
```
也可以用其他可视化方案，核心数据就是 data 列表， ``sys`` 是相应的 xa.mul 对象

**Comment by pang123hui** [comment]
感谢回复，测试了下，没问题。

`date = []
data = []
for d in pd.date_range("2020-03", "2020-10", freq="W"):
    data.append(sysopen.summary(d.strftime("%Y-%m-%d")).iloc[0]["基金收益总额"])
    date.append(d.strftime("%Y-%m-%d"))
from pyecharts.charts import Line
line=Line()
line.add_xaxis(xaxis_data=date)
line.add_yaxis(series_name="总收益",y_axis=data, is_symbol_show=False)
line.render_notebook()`

改了两次，显示看着舒服一些，并且可以在jupyter可视化直接显示，方便一些

**Comment by pang123hui** [comment]
date = []
data = []
data2 = []
for d in pd.date_range("2020-03", data_today, freq="W"):
#    data.append(sysopen.summary(d.strftime("%Y-%m-%d")).iloc[0]["基金收益总额"])
    data2.append(sysopen.summary(d.strftime("%Y-%m-%d")).iloc[0]["基金现值"])
    date.append(d.strftime("%Y-%m-%d"))
from pyecharts.charts import Line
from xalpha.cons import line_opts
vopts = line_opts
line=Line()
line.set_global_opts(**vopts)
line.add_xaxis(xaxis_data=date)
#line.add_yaxis(series_name="总收益",y_axis=data, is_symbol_show=False)
line.add_yaxis(series_name="总额",y_axis=data2, is_symbol_show=False)
line.render_notebook()

再改一下，设置了set_global_opts，这样就完美了，不然鼠标指上去没反应
