### ISSUE TITLE
backtest中，多个策略形成一个持仓组合

### ISSUE THREAD

**Issue by laye0619** [refraction-ray/xalpha#62]
如果我想实现几个不同的策略，例如28轮动，网格等等，形成一个持仓组合，并且定期从大的仓位上做再平衡。

我的思路是继承一个BTE作为持仓组合策略，里面实例化不同的策略，然后将各个策略backtest()以后的结果，合并trades，并作为参数实例化mul或者mulfix

不知类似这种情况还有没有好的建议？

**Comment by laye0619** [comment]
其实我的需求是要实现一个多策略组合持仓并定期动态再平衡的策略。现在目前好像框架比较难实现这一个。
例如，通过全市场估值确定股票总仓位，剩下的资金买货币基金；股票总仓位重，40%根据指数宽基估值低买高卖，30%进行行业指数轮动；20%进行28轮动。。。；每个季度进行仓位再平衡。。。

**Comment by laye0619** [comment]
现有框架下，有没有啥好思路建议来实现这个？

**Comment by refraction-ray** [comment]
需求感觉上有点复杂，可能得自己写一个回测子类？感觉现在的框架回测类的嵌套（将一些回测类视为一个基金在另一个更高层的回测类里交易）可能不是特别好处理。可能就是一个单独的回测类，然后把你上面描述的交易逻辑都写在里边反而是最直接的办法了。

**Comment by laye0619** [comment]
思路这样：分别实现回测子类，实现不同策略。再单独实现一个回测子类，模拟持仓组合，在run()里面分别调用各个策略的run()，然后持仓组合回测子类里面backtest来做trade item的合并，最终获取mulfix。我先搞搞，有成果一起交流

**Comment by happyTonakai** [comment]
大佬有什么新进展吗？我也有个类似的想法，策略倒是没你的那么复杂，50%主动管理基金，50%债券基金，每季度做一次动态平衡。再复杂一点的话可能就是根据整体估值分位来确定股债比例这样
