### ISSUE TITLE
indicator.py中对beta函数的实现有些疑问

### ISSUE THREAD

**Issue by Razorro** [refraction-ray/xalpha#64]
`return res.loc["bcmk", "bt"] / res.loc["bcmk", "bcmk"]` 分母为什么是benchmark的方差呢？从公式上不是应该是两组数据的方差乘积的平方吗?

**Comment by Razorro** [comment]
似乎明白了，这里潜在是用的single index model做的回归，可以这么理解吗？但是如果仅仅是两个任意基金收益变动率做回归，总感觉没有什么统计上的意义...

**Comment by refraction-ray** [comment]
如果我对你的话的理解是对的话，那你的理解是对的。
这里的 beta 确实是针对 single index 的，indicator 类里的指标其实都是针对一个标的的，整个 indicator 就是标的类的一个 mixin。所以 benchmark 通常是选市场基准指数作为一个标尺。如果随便选一个基金作为 benchmark 的话，确实计算出的 beta 没什么意义。你想要用的量可能是两个标的之间的 **correlation** 而非某个标的的 **beta**。多个标的的 correlation 计算的话，可以参考 ``xa.Compare`` 类

**Comment by Razorro** [comment]
了解，感谢解答！
