### ISSUE TITLE
怎么将K线图和别的Indicator放在一起，例如MA，bollinger bands

### ISSUE THREAD

**Issue by willzhqiang** [refraction-ray/xalpha#65]
如题，我看作者indicator.py里面有Indicator这个class，但是没看懂怎么用。比如我想把700的MA5、MA10，bollinger bands这些画到一张图上，该怎么写代码呢？

**Comment by refraction-ray** [comment]
这部分我之前也没有特别仔细地想过，为了实现你说的这个，我又更新了下代码。现在可以用下面的代码来做到

```python
tencent = xa.vinfo("HK00700", start="2012-01-01", normalization=False)
for window in [5, 10, 20, 60]:
    tencent.ma(window)
tencent.price.v_kline(col=["MA5", "MA10", "MA20", "MA60"])
```
显示效果如下

<img width="1140" alt="Screen Shot 2020-11-08 at 4 28 23 PM" src="https://user-images.githubusercontent.com/35157286/98460440-74723f00-21df-11eb-91ff-1ea0c902a749.png">

相应其他的技术指标同理，需要打出 tencent.price 看看对应的表头栏名称。当然很多指标都是很久之前写的，也可能有些错误或兼容性问题（其实这些指标都是基于收盘价计算的，因为最早这个库只处理基金，所以很多需要low high open close 四个值的指标做了近似或没写，实现一个完整的 klineindicator 类也是一个未来的规划）。中间有任何问题的话，欢迎反馈。
