### ISSUE TITLE
大佬，有没有。获取全市场所有基金和指数代码的接口函数

### ISSUE THREAD

**Issue by wangshuile** [refraction-ray/xalpha#68]
大佬，有没有。获取全市场所有基金和指数代码的接口函数.我希望，实现扫描A股所有的基金，计算收益率最高的，那几只基金。

**Comment by refraction-ray** [comment]
可以用 xa.misc.get_fund_list(str), str 可以是 "hh", "zq", "zs", "gp", "qdii" 等，对应混合基金，债券基金，指数基金，股票基金和 qdii 基金等

**Comment by wangshuile** [comment]
感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "refraction-ray"<notifications@github.com&gt;; 
发送时间: 2020年11月19日(星期四) 晚上7:12
收件人: "refraction-ray/xalpha"<xalpha@noreply.github.com&gt;; 
抄送: "2027429742"<2027429742@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [refraction-ray/xalpha] 大佬，有没有。获取全市场所有基金和指数代码的接口函数 (#68)





 
可以用 xa.misc.get_fund_list(str), str 可以是 "hh", "zq", "zs", "gp", "qdii" 等，对应混合基金，债券基金，指数基金，股票基金和 qdii 基金等

**Comment by happyTonakai** [comment]
天天基金接口失效，返回空列表

https://github.com/refraction-ray/xalpha/blob/a8ca84c64c5da0bc29efa35ad7bf70252510bea2/xalpha/misc.py#L214-L227
