### ISSUE TITLE
bte是否可以用模拟运行review

### ISSUE THREAD

**Issue by laye0619** [refraction-ray/xalpha#69]
如题 自己实现的bte class 回测策略 能不能用review 来模拟运行并收到通知呢

**Comment by refraction-ray** [comment]
首先，realtime 模块将来可能不再后续开发和跟进了，当然其中发邮件的函数 ``mail`` 总是可以单独使用的。

想将这个邮件提醒和回测模块结合需要注意的是：一般来讲回测模块只会获取历史日线数据进行分析和交易，并截止到昨日。这个回测模块由于数据原因，不支持高频的策略。那么想要把它用到判断今日需要的交易情况，需要先将实时的数据视为收盘数据，然后单独写个和 run 逻辑差不多的函数就好了，比如 ``rtrun``，把判断今日是否交易怎么交易并且邮件提醒的逻辑都写到里边。每天调用时，可以
```python
class myBTE(BTE):
    def run():
          pass
    def rtrun():
          # 获取实时数据
          # 判断是否交易
          # 发送邮件
bteobj = myBTE()
bteobj.backtest()
bteobj.rtrun() # 此时判断今日应该的交易情况，并发送邮件
```

**Comment by laye0619** [comment]
十分感谢
