### ISSUE TITLE
申购费问题

### ISSUE THREAD

**Issue by Aaron-YunZhao** [refraction-ray/xalpha#7]
您好，谢谢强大的分享！
请问在单只基金交易的分析，或多只基金投资组合的管理分析中，申购费如何考虑的？我的疑虑是，比如1.5%申购费的基金，在很多销售平台1折销售，即实盘中0.15%，这个如果没有考虑，对收益率的影响还是蛮大的。谢谢。

**Comment by refraction-ray** [comment]
申购费是直接抓去的天天基金实际收取的费率，也即绝大部分都是一折，这点可以放心。如果有基金的申购费率和自己买的销售渠道费率不符的话，也可以手动 `fundinfo_obj.rate=0.12` 这样来调掉。
根据我的经验绝大部分基金费率是可以和销售平台完全对上的。存在极少数基金，倒不是折扣不对，而是天天基金申购费率为空，不过我只遇到过一只。
一般来讲，读取账单得出的汇总数据是可以和实盘对比，一分不差的。

**Comment by Aaron-YunZhao** [comment]
谢谢，明白了！小建议，是否可以在dailyreport里面加一列“手续费”？
另外，请问怎么调整现金分红和红利再投？

**Comment by refraction-ray** [comment]
@Aaron-YunZhao , 在账单中，若对应分红日“分”位是5，则表示红利再投。比如 0228 某只基金的分红日，账单对应记录 1000.05 则代表申购1000元，同时该日分红策略是红利再投。否则默认是现金分红。https://xalpha.readthedocs.io/en/latest/xalpha.html#xalpha.record.record 有一些说明。
dailyreport 添加展示项很容易，我有时间看一下，加更多项进去。

**Comment by Aaron-YunZhao** [comment]
@refraction-ray Great thanks! Very powerful codes and docs.
对于习惯红利再投的可能不是非常方便，因为需要手动去找到每一笔基金分红，然后去账单中每一笔记录‘’0.05”。而且实盘中分红通知日期比实际发生晚1-2天，而且通常不会通知实际发生日期，所以记录容易出错。（当然，您的fund.speical里可以查到确切分红日。）
能否实现在账单中一笔设置就改变后续所有交易红利方式？谢谢。

**Comment by refraction-ray** [comment]
我会仔细考虑一下怎么设计 API 更好一些。比如是在账单上额外记录还是对 fundinfo 对象给参数，使得可以默认红利再投。暂时没想到特别好的，不 confusing 的方案。比如如果基金组合允许每只基金分别设定默认现金分红或红利再投的话，记账单可能比较 confusing。好在基金分红情况其实很少，10%的基金顶多一年分红一次，其他基金几乎从不分红，因此需要单独记 0.05 的时候应该次数不多。

**Comment by Aaron-YunZhao** [comment]
@refraction-ray 组合里如果有货币基金就比较讨厌了，如004137，天天分红强制再投 ;-(

**Comment by refraction-ray** [comment]
这种货币基金可以直接调用 `mfundinfo` 类，都可以处理成净值型的，不会视为分红，所以不需要每天标记0.05就可以。如果读取账单做基金组合的话，是可以自动识别基金代码是货币基金还是其他基金的。

**Comment by Aaron-YunZhao** [comment]
@refraction-ray mfund处理成净值会导致记录净值高于实际（1），而份额低于实际，买入一直持有不会有问题，如下买入10000并持有，
![image](https://user-images.githubusercontent.com/54311143/76382372-7c00f000-6393-11ea-9801-d298858fae2f.png)
但如果中间部分卖出，那剩余持仓就会有问题，如下买入10000后续卖出5000，
![image](https://user-images.githubusercontent.com/54311143/76382725-98515c80-6394-11ea-830d-a836ee5e616b.png)
原因在于实盘和记录中份额净值的偏差。暂时解决办法可以是手动找到卖出日dailyreport中的虚拟净值x，账单中记录为-5000/x。

**Comment by refraction-ray** [comment]
对的，这是本身设计买入记录金额，卖出记录份额决定的。当净值不为1时，卖出记录的数目是份额而不是金额。将货币基金统一用净值处理，是为了内部接口和其他基金统一。对于货币基金卖出的记录肯定是不太方便的，也许我有时间可以改一下  mfundinfo 类的 shuhui 接口。

**Comment by refraction-ray** [comment]
关于货币基金按金额赎回和默认基金分红再投入两点，都添加了新选项，具体可参考 https://xalpha.readthedocs.io/en/latest/xalpha.html#xalpha.record.record。也即通过在记账单添加一行，或向 mul 传入 property 字典参数，都可以改变每只基金的默认行为。具体的默认分红再投是2，赎回视为金额是 4.

**Comment by Aaron-YunZhao** [comment]
Thanks for updates, very useful and convenient. :)
