### ISSUE TITLE
日期更新了，收益率没有重新计算

### ISSUE THREAD

**Issue by qiuning79** [refraction-ray/xalpha#70]
我写了段代码想计算某只基金年初至今的收益率：
fund_info = xa.fundinfo(code) # 交易标的信息
st = xa.policy.buyandhold(fund_info, start=”2019-12-31“)
sys = xa.trade(fund_info, st.status)
total_return = sys.dailyreport()['投资收益率'][0]/100

这段代码第一次计算的收益率是正确的。但如果不退出程序，到了第二天、第三天再调用这段代码计算的收益率还是停留在第一天相同的数值上，并没有随着日期和净值的更新重新计算收益率。
请问，应该怎样写，收益率才能再后续日期的运行中更新呢？多谢！

**Comment by refraction-ray** [comment]
这个原因可能是``dailyreport(date)``的默认日期没变，这是我之前代码实现上有点偷懒造成的。解决方案是手动传进参数 ``dailyreport(date=xa.cons.yesterdatobj())``. 你可以看下这样结果是不是对的。

**Comment by qiuning79** [comment]
如果传入参数dailyreport(date=xa.cons.yesterdatobj())，会提示错误xa.cons.yesterdatobj()找不到。
我看trade.py代码中def dailyreport(self, date=yesterdayobj()):，date已经给了默认参数yesterdayobj()了，yesterdayobj就是计算昨天日期时间的：
# datetime obj for yesterdate date with time set to be 0:0:0
yesterdayobj = lambda: (dt.datetime.now(tz_bj).replace(tzinfo=None) - dt.timedelta(1))

**Comment by refraction-ray** [comment]
报错找不到的话就先 ``from xalpha.cons import yesterdayobj`` 试一下吧。默认参数确是这个函数，之所以不生效，是因为 python 解释器会在第一次就把所有的默认参数带的函数跑出结果了，所以一旦你的程序过了一天一直没停，对应的日期就是错的了。简单说正确的实现应该是
```
def somefunc(date=None):
    if date is None:
        date = yesterdayobj()
```
现在的 ```def somefunc(date=yesterdayobj())``` 是一个错误示范，只是我太懒没有改正而已（因为很少有程序连续跨天的需求）。
解决办法就是调用时，重新手传 ``somefunc(date=yesterdayobj())``。这几个区别比较的确绕，需要对 python 解释器怎么工作比较清楚。

**Comment by qiuning79** [comment]
多谢大佬的解释，我理解其中的原因了，谢谢！
