### ISSUE TITLE
账单的csv文件如何生成的

### ISSUE THREAD

**Issue by sdu2011** [refraction-ray/xalpha#8]
自己手动记录吗?

**Comment by refraction-ray** [comment]
是的。我也曾经有过将支付宝基金账单这种直接导出处理的想法。但我发现支付宝导出的账单有个硬伤，赎回记录的是金额不是份额，但按赎回金额是无法精确的推出赎回份额的（可能有0.01的误差），因此我就没做。

**Comment by sdu2011** [comment]
就在这个issue讨论吧
csv
```
date,163411,001938,519772,163402
20200221,20000,,
20200310,,,5000
20200310,,4000,
20200313,,,1000,3000
20200313,,2000,
20200323,,3506,
```

```
#coding=utf-8
import sys
sys.path.insert(0, "../../")

import xalpha as xa
print(xa.__path__)
from datetime import date

from datetime import date
from datetime import datetime, timedelta
today = date.today()
today = today.strftime("%Y-%m-%d")

status=xa.record("../tests/fund_2020.csv").status
zosd = xa.fundinfo('001938')
zosd_t = xa.trade(zosd,status)
print(zosd_t.dailyreport())
```
这个我不确定是代码bug还是我用的不对　这个dailyreport输出是不对的
```
        基金名称    基金代码    当日净值  单位成本    持有份额     基金现值   基金总申购  历史最大占用  基金持有成本  基金分红与赎回       换手率  基金收益总额   投资收益率
0  中欧时代先锋股票A  001938  1.5418  1.59  4720.9  7278.68  7506.0  7506.0  7506.0      0.0  7.604167 -227.32 -3.0285
```
这里的份额总额都是错的.

[fund.py](https://github.com/sdu2011/xalpha/blob/master/xalpha/fund_2020.py)
这是我自己的统计脚本,统计出来是准确的.

**Comment by refraction-ray** [comment]
你的 csv 好像逗号数目有问题，似乎列数没对上

**Comment by sdu2011** [comment]
> 你的 csv 好像逗号数目有问题，似乎列数没对上

一样的　测试过了　最后一列的逗号可加可不加的

**Comment by sdu2011** [comment]
统计某个主动基的历史最大回撤　这个功能有吗

**Comment by refraction-ray** [comment]
> 统计某个主动基的历史最大回撤　这个功能有吗

这个有的，先 ``info.bcmkset()``, 然后 ``info.max_drawdown()`` 就好了。

> 一样的　测试过了　最后一列的逗号可加可不加的

账单上其他几个基金的数据能对上吗，是只有这一个有问题还是？

**Comment by sdu2011** [comment]
> > 统计某个主动基的历史最大回撤　这个功能有吗
> 
> 这个有的，先 `info.bcmkset()`, 然后 `info.max_drawdown()` 就好了。
> 
> > 一样的　测试过了　最后一列的逗号可加可不加的
> 
> 账单上其他几个基金的数据能对上吗，是只有这一个有问题还是？

好的,我试下.   其他的数据对的上的.

**Comment by refraction-ray** [comment]
我又看了下，那个csv账单格式里，最好一个日期的记录都在一行，一个日期多行可能有问题，不知道对不上是不是和这个有关系

**Comment by sdu2011** [comment]
> 我又看了下，那个csv账单格式里，最好一个日期的记录都在一行，一个日期多行可能有问题，不知道对不上是不是和这个有关系

是的　一个日期只记录在一行结果就对啦

**Comment by sdu2011** [comment]
测试了163402,回撤感觉不大对啊. 我查看了天天基金上的单位净值和累积净值,在'2017-08-22 00:00:00'之后没有突变的情况.
```
def f(code_list):
    for code in code_list:
        fund_info = xa.fundinfo(code)
        hs300 = xa.indexinfo('0000300')
        
        fund_info.bcmkset(hs300,start='2017-01-01')
        print(fund_info.v_netvalue())
        
        print(fund_info.name,fund_info.max_drawdown())
    
f(jjcode_list)
```
```
兴全趋势投资混合(LOF) (Timestamp('2017-08-22 00:00:00'), Timestamp('2018-10-18 00:00:00'), -0.46409872849663425)
```

**Comment by refraction-ray** [comment]
最大回撤不是单日回撤，返回不是指明了有时间段么

**Comment by sdu2011** [comment]
> 最大回撤不是单日回撤，返回不是指明了有时间段么

我说没有净值突变的情况是指时间段内没有特殊情况(比如分红啊之类的导致程序可能统计不准)，并不是说单日回撤四十六。

**Comment by sdu2011** [comment]
> > 最大回撤不是单日回撤，返回不是指明了有时间段么
> 
> 我说没有净值突变的情况是指时间段内没有特殊情况(比如分红啊之类的导致程序可能统计不准)，并不是说单日回撤四十六。

程序给出的这段时间我查了，最大回撤没这么多。手机打字不便，不知说清楚了没有。

**Comment by refraction-ray** [comment]
那个回撤数是百分比的意思，大概是下跌了 46% ，不知道这样是不是对上的。

**Comment by sdu2011** [comment]
> 那个回撤数是百分比的意思，大概是下跌了 46% ，不知道这样是不是对上的。

兴全趋势投资混合(LOF),date:20170822单位净值为:1.0696
兴全趋势投资混合(LOF),date:20181018单位净值为:0.5732
46%似乎是按照单位净值算出来的.    

查了下天天基金数据,在这个时间段内发生过两次分红,应该是这个导致最大回撤数据没能反映真实情况
![image](https://user-images.githubusercontent.com/6041743/78532483-ea619280-7819-11ea-9b60-21c70d198710.png)

这个有办法解决吗?

**Comment by refraction-ray** [comment]
没有很好的办法，因为指标分析都是按照 netvalue 列来的，如果你只是单纯想分析技术指标而不用来做交易的话，应该可以用下面的 workaround

```python
xq = xa.fundinfo("163402")
xq.price["netvalue"] = xq.price["totvalue"]
xq.bcmkset(xa.indexinfo("0000300"))
xq.max_drawdown()
```
不过这个改造过的 info 去做 trade 应该会有问题，看技术指标还行

**Comment by sdu2011** [comment]
> ```python
> xq.price["netvalue"] = xq.price["totvalue"]
> ```

懂了　Ｏ（∩＿∩）Ｏ谢谢
