### ISSUE TITLE
AssertionError: 自定义申购费必须为正值

### ISSUE THREAD

**Issue by aaronyunzhao** [refraction-ray/xalpha#84]
从蛮老的v0.8左右版本升级到最新版本v0.11.2 - 2021.01.01后，运行交易账单，其中一个账单会出现如下error

`c:\users\aaron\appdata\local\programs\python\python38\lib\site-packages\xalpha\multiple.py in __init__(self, status, istatus, property, fetch, save, path, form, *fundtradeobj)
     92                 try:
     93                     fundtradeobj.append(
---> 94                         trade(
     95                             fundinfo(
     96                                 code,

c:\users\aaron\appdata\local\programs\python\python38\lib\site-packages\xalpha\trade.py in __init__(self, infoobj, status, cftable, remtable)
    326         self.status = status.loc[:, ["date", code]]
    327         self.status = self.status[self.status[code] != 0]
--> 328         self._arrange()
    329 
    330     def _arrange(self):

c:\users\aaron\appdata\local\programs\python\python38\lib\site-packages\xalpha\trade.py in _arrange(self)
    337                     break
    338                 else:
--> 339                     raise e
    340 
    341     def _addrow(self):

c:\users\aaron\appdata\local\programs\python\python38\lib\site-packages\xalpha\trade.py in _arrange(self)
    332         while 1:
    333             try:
--> 334                 self._addrow()
    335             except Exception as e:
    336                 if e.args[0] == "no other info to be add into cashflow table":

c:\users\aaron\appdata\local\programs\python\python38\lib\site-packages\xalpha\trade.py in _addrow(self)
    380                     feelabel = None
    381                 value = int(value * 100) / 100
--> 382                 assert feelabel is None or feelabel >= 0.0, "自定义申购费必须为正值"
    383                 rdate, cash, share = self.aim.shengou(value, date, fee=feelabel)
    384                 rem = rm.buy([], share, rdate)

AssertionError: 自定义申购费必须为正值`

**Comment by refraction-ray** [comment]
这个比较奇怪，一般来讲报错的这个地方是处理自定义手续费的，比如账单里的 200.00515 表示申购了 200 份额，手续费率是1.5%。这个 feelabel 此时就是 1.5 大于 0. 而以前一般的账单记法 feelabel 默认处理成 None，所以 ``assert feelabel >= 0.0`` 这个地方，比较难直接想到为什么会 fail。也许你尝试一下更少条目的账单，来看一下到底是哪个单元格的数值会报错（还是很多都会报），我们再进一步分析？

**Comment by aaronyunzhao** [comment]
原因可能是，我的该账单中有些基金是转换购买的，金额数字有到小数点后5位，可能是不是和你定义的小数点交易有关？我把这些小数点舍弃到3位，就一切正常了。

**Comment by refraction-ray** [comment]
那应该就是这个原因，不过转换购买可以有小数点后那么多位也挺奇怪的，因为基金份额反正最多只能认证到小数点后两位
