### ISSUE TITLE
fundinfo: 没有2021的数据

### ISSUE THREAD

**Issue by liuyang1** [refraction-ray/xalpha#86]
通过xa.fundinfo获取基金的净值信息，发现缺少2021年的数据
通过xa.rfundinfo获取，则缺少2021年除当天之外的其他数据

**Comment by refraction-ray** [comment]
升级一下 xalpha 的版本就好了，see https://github.com/refraction-ray/xalpha/issues/85

**Comment by liuyang1** [comment]
👍👍👍
