### ISSUE TITLE
支持获取港股秒级的数据

### ISSUE THREAD

**Issue by tsuiyuenhong** [refraction-ray/xalpha#87]
请问目前支持获取港股历史秒级数据吗

**Comment by tsuiyuenhong** [comment]
xa.get_bar('xxxx', interval=1, prev=330)

发现如果 interval 写 1 会抛异常

**Comment by refraction-ray** [comment]
港股是雪球的数据源，最小的粒度应该是 1min，而且应该只有最近一段时间的数据，无法取到较早的历史数据

**Comment by tsuiyuenhong** [comment]
我看了下 get_bar 这个 api 还有点问题，假设传的日期是今天，数据是不够一天的。理论每天数据是有 60*60*5.5 条的，但是如果某个时间没有交易，雪球会返回空。

**Comment by refraction-ray** [comment]
嗯，比日线粒度小的数据，可靠性都没什么保证。没什么靠谱的免费源
