### ISSUE TITLE
账户基金代码6位补全

### ISSUE THREAD

**Issue by aaronyunzhao** [refraction-ray/xalpha#9]
由于习惯在excel里编辑账户，保存后代码开头的0数字都会消失。

试着在read.status得到df后通过添加一行`read.status.columns=[['date'] + [x.zfill(6) for x in df.columns[1:]]]`有效。

于是又想一劳永逸，试着把这行代码加入您的record源文件中，运行遇到Pandas warning: column creation via attribute name，显示在`df.data=[`这一行，于是试着把`df.date` 修改成`df['date']`，结果更多报错，目前没找到原因。

    def __init__(self, path="input.csv", format="matrix", **readkwds):
        df = pd.read_csv(path, **readkwds)
        df.columns=[['date'] + [x.zfill(6) for x in df.columns[1:]]]
        if format == "matrix":
            df.date = [
                # pd.Timestamp.strptime(str(int(df.iloc[i].date)), "%Y%m%d")
                # higher version of pandas timestamp doesn't support strptime anymore? why? what is the gain here?
                pd.to_datetime(str(int(df.iloc[i].date)), format="%Y%m%d")
                for i in range(len(df))
            ]
            df.fillna(0, inplace=True)
            self.status = df

**Comment by refraction-ray** [comment]
如果把 ``df.columns=[['date'] + [x.zfill(6) for x in df.columns[1:]]]`` 移到 ``self.status = df`` 这句之前呢

**Comment by aaronyunzhao** [comment]
> 如果把 `df.columns=[['date'] + [x.zfill(6) for x in df.columns[1:]]]` 移到 `self.status = df` 这句之前呢

同样的报错：
    274 
    275         self._url = (
--> 276             "http://fund.eastmoney.com/pingzhongdata/" + code + ".js"
    277         )  # js url api for info of certain fund
    278         self._feeurl = (

TypeError: can only concatenate str (not "tuple") to str

**Comment by refraction-ray** [comment]
这个报错似乎是说明，记账单的 column 不是字符串格式，而是变成 tuple 了，你确定 columns = [[]] 而不是 [] 吗，我没去查文档，应该是个column 改后的格式问题

**Comment by aaronyunzhao** [comment]
确认是这个原因，去掉就一切OK了，谢谢。修改如下。
PS其它几个module我也有一点点个人偏好的修改，整理好了想pullrequest给你帮忙指导一下。

    def __init__(self, path="input.csv", format="matrix", **readkwds):
        df = pd.read_csv(path, **readkwds)
        df.columns = ['date'] + [x.zfill(6) for x in df.columns[1:]]
        if format == "matrix":
            df['date'] = [
                # pd.Timestamp.strptime(str(int(df.iloc[i].date)), "%Y%m%d")
                # higher version of pandas timestamp doesn't support strptime anymore? why? what is the gain here?
                pd.to_datetime(str(int(df.iloc[i].date)), format="%Y%m%d")
                for i in range(len(df))
            ]
            df.fillna(0, inplace=True)
            self.status = df

**Comment by refraction-ray** [comment]
欢迎 PR，如果有新 feature 记得加个测试

**Comment by aaronyunzhao** [comment]
@refraction-ray 
计算一个封闭系统的年化收益时，请问怎么理解total_annualized_returns()和xirrrate()所得结果的差异？

**Comment by refraction-ray** [comment]
> 计算一个封闭系统的年化收益时，请问怎么理解total_annualized_returns()和xirrrate()所得结果的差异？
大概相当于一个是基金的净值年化收益，一个是你买卖这个基金的真实年化收益。一个基金年初净值1.0到年末1.2，但你的交易仍旧可能是亏损的。

**Comment by refraction-ray** [comment]
如果是封闭系统，这两个应该很接近，你是有差很多的例子吗

**Comment by aaronyunzhao** [comment]
开放系统貌似没法使用total_annualized_returns()
封闭系统差异不大，我试过的都在小数点第4位。只是想了解计算区别在哪？

目前想得到一段自定义时间段内的年化，xirrrate()无法定义start date，total_annualized_returns()可以通过bcmkset定义。开放系统下又没法定义benchmark。

**Comment by refraction-ray** [comment]
@aaronyunzhao , 计算上， anunalized return 就是最后日期的总资产金额除以开始的，然后按总天数开方就好了，比较简单。但是这种计算肯定不适用于开放系统，开放系统的投入金额怎么定义，总天数又怎么定义，这都是问题。
xirr 就是内部收益率，这个可以考虑到每一笔现金投入的时间成本，计算时首先增加一笔现在的全部卖出，然后对所有的现金流计算 c_1/t_1^r+c_2/t_2^r+...=0, 这个方程的解r，就是内部收益率，它并较准确的刻画了开放系统的年化情况。
两个收益率在封闭系统理论上是一样的，但由于 xirr 需要数值解方程，肯定会有一个误差，所以才会不完全一样。（其实还有 xirr 考虑了赎回费， returns 没考虑的因素）
至于开放系统定义一定时间内的收益率，这个问题就是，之前持有的资产怎么算？因为 xirr 计算需要每一笔现金流，那一定时间之前的现金流怎么考虑？如果完全不管的话，你可以从交易账单开始就截掉 `status = status[status["date"]>"2019-01-01"]`。但是你确定这是你想要的情形吗，如果19年之后卖出的比买入的多呢，这个截断的账单就又矛盾了。
总结下就是，只有封闭的系统可以计算 annulized return，只有现金流闭合的系统（买入卖出全部能对上，不能有最后没卖掉的，也不能卖不存在的），才能计算 xirr。这是理论和现实所限制的，而不是程序。

**Comment by aaronyunzhao** [comment]
> @aaronyunzhao , 计算上， anunalized return 就是最后日期的总资产金额除以开始的，然后按总天数开方就好了，比较简单。但是这种计算肯定不适用于开放系统，开放系统的投入金额怎么定义，总天数又怎么定义，这都是问题。
> xirr 就是内部收益率，这个可以考虑到每一笔现金投入的时间成本，计算时首先增加一笔现在的全部卖出，然后对所有的现金流计算 c_1/t_1^r+c_2/t_2^r+...=0, 这个方程的解r，就是内部收益率，它并较准确的刻画了开放系统的年化情况。
> 两个收益率在封闭系统理论上是一样的，但由于 xirr 需要数值解方程，肯定会有一个误差，所以才会不完全一样。（其实还有 xirr 考虑了赎回费， returns 没考虑的因素）
> 至于开放系统定义一定时间内的收益率，这个问题就是，之前持有的资产怎么算？因为 xirr 计算需要每一笔现金流，那一定时间之前的现金流怎么考虑？如果完全不管的话，你可以从交易账单开始就截掉 `status = status[status["date"]>"2019-01-01"]`。但是你确定这是你想要的情形吗，如果19年之后卖出的比买入的多呢，这个截断的账单就又矛盾了。
> 总结下就是，只有封闭的系统可以计算 annulized return，只有现金流闭合的系统（买入卖出全部能对上，不能有最后没卖掉的，也不能卖不存在的），才能计算 xirr。这是理论和现实所限制的，而不是程序。

谢谢解答，受益匪浅。

**Comment by aaronyunzhao** [comment]
又找个几个例子，有的差异还是很大的，如下。赎回费造成的？

`xf = xa.fundinfo('519732')`
`bill = xa.policy.buyandhold(xf, start='20191230') `
`sysclose = xa.mulfix(xa.trade(xf, bill.status), totmoney=100001)`
`sysclose.bcmkset(xa.indexinfo('0000300'))`
`sysclose.xirrrate(), sysclose.total_annualized_returns()`

Out: (0.38953538508434477, 0.4285)

**Comment by aaronyunzhao** [comment]
另一个例子。查了一下赎回费0.5%，也对不上。
倒是total_annualized_returns()总是都比xirrrate()好。

```
xf = xa.fundinfo('110022')
bill = xa.policy.buyandhold(xf, start='20191030')
trade = xa.trade(xf, bill.status)
sysclose = xa.mulfix(trade, totmoney=100001) 
sysclose.bcmkset(xa.indexinfo('0000300'))
sysclose.xirrrate(), sysclose.total_annualized_returns()

Out: (-0.13072851116406686, -0.1166)
```

**Comment by refraction-ray** [comment]
@aaronyunzhao , 天数短的时候，可能收益年化会比较敏感，你把时间改成 20190101 似乎区别就不大了

**Comment by refraction-ray** [comment]
@aaronyunzhao , 我又想了一下，xirr 是可以计算分段时间的收益率的，操作是把那之前的所有持仓视为计算时间段第一天的现金流入。最新的 commit 已经支持了 ``mul.xirrrate(date=end, startdate=start)`` 可以计算从 startdate 到 date 的年化收益率，封闭和开放系统均可。

**Comment by aaronyunzhao** [comment]
> @aaronyunzhao , 我又想了一下，xirr 是可以计算分段时间的收益率的，操作是把那之前的所有持仓视为计算时间段第一天的现金流入。最新的 commit 已经支持了 `mul.xirrrate(date=end, startdate=start)` 可以计算从 startdate 到 date 的年化收益率，封闭和开放系统均可。

赞！对于了解账户某一段时间内的得失非常方便了。
