### ISSUE TITLE
get_industry_holdings 和  get_industry 返回持股行业比例不一致问题

### ISSUE THREAD

**Issue by wyjbird** [refraction-ray/xalpha#90]
以兴全趋势163402为例：
get_industry_holdings('2020','4','12') 返回结果：
{'有色金属': 8.91,
 '电子': 5.58,
 '机械设备': 5.32,
 '非银金融': 4.75,
 '交通运输': 4.61,
 '房地产': 8.11,
 '建筑材料': 3.54,
 '医药生物': 2.94,
 '休闲服务': 2.88}  
**可以看出有色比房地产多；**

get_industry   返回结果：
{'有色金属': 861.2605109753069, '商业贸易': 634.6723398941072, '交通运输': 578.3071232072414, '非银金融': 568.1613842036056, '房地产': 1085.594073389032, '机械设备': 537.7241671926981, '电子': 447.53982049371325, '休闲服务': 454.30364649613705, '建筑材料': 372.0104301333132, '化工': 356.22816946099084, '医药生物': 251.38886642342075, '国防军工': 600.8532098819877, '食品饮料': 214.1878234100894, '家用电器': 179.24138906423275, '轻工制造': 164.58643272564768, '通信': 135.27652004847752}

**可以看出房地产比有色多；**

请问 这是怎么回事呢？

**Comment by refraction-ray** [comment]
可能是默认用的基金季报周期不一样？或者可以给出完整的代码吗？

**Comment by wyjbird** [comment]
我看了您的源代码：def get_industry(self, date=yesterdayobj()):
        """
        获取基金组合持仓的行业占比信息，底层为非 A 股持仓的暂不支持

        :param date:
        :return: Dict
        """
        # TODO: hard coded 一个字典来合并一些二级行业
        d = {}
        date = convert_date(date)
        rd = date - pd.Timedelta(days=120)

这里  是不是基金组合的默认-120天（四个月）  导致季报是第三季度 而不是昨天（第四季度）？

**Comment by wyjbird** [comment]
哦 我给get_industry 赋了个参数 让它先30天之后 再进入方法里减去120天 与单只的对上了 我知道问题了 谢谢

**Comment by refraction-ray** [comment]
嗯，那应该就是默认季报不一样的问题。因为有时特殊情况季报出得晚，所以不指定时间我都会默认去找比较早的季报，保证是有的
