### ISSUE TITLE
Javascript Error in Jupiter lab

### ISSUE THREAD

**Issue by killandy** [refraction-ray/xalpha#92]
习惯用的jupyter lab，所以就直接在lab上跑，而不是notebook，但在执行示例文件的时候出现问题：
```
import xalpha as xa
import pandas as pd
xa.set_display("notebook")
```
出现错误：
`Javascript Error: Can't find variable: require`

而在jupyter notebook是正常运行的。

**Comment by refraction-ray** [comment]
是的。jupyter lab 对于 js 脚本之类的支持，相比 jupyter notebook 退化了，可能导致 ``xa.set_display("notebook")`` 不可用. 暂时没什么好办法。
