### ISSUE TITLE
定投策略测试发现的问题

### ISSUE THREAD

**Issue by bobbypiggy** [refraction-ray/xalpha#93]
import xalpha as xa
import pandas as pd
import matplotlib.pyplot as plt
from tqdm import tqdm

#正常显示画图时出现的中文和负号
from pylab import mpl
mpl.rcParams['font.sans-serif']=['SimHei']
mpl.rcParams['axes.unicode_minus']=False

plt.style.use('dark_background')

# 可以先生成IO的设置字典，save 字段表示每一个info对象会自动将信息本地化，fetch 字段表示初始化时先尝试本地获取， 
# path 字段是存储的路径和前缀, form 字段表示存储的格式是 csv
# 指数，基金和货币基金类都可以使用这种增量更新策略来提速
ioconf={'save':True,'fetch':True,'path':'./fund_data/', 'form':'csv'}

fund_num = '005335'
fund_info = xa.fundinfo(fund_num, **ioconf)

start_time = '2017-06-17'
end_time = '2021-01-01'

# 按照每周三定额定投1000，生成交易单
auto = xa.policy.scheduled(fund_info, 1000, pd.date_range(start_time, end_time, freq='W-THU'))

# 按上面的策略单子交易下
fund_final = xa.trade(fund_info, auto.status)

*******************************************************************
会生成如下的warning信息：
账单日期 2018-02-15 00:00:00 非 005335 的净值记录日期，日期智能平移后 2018-02-22 00:00:00 与账单其他日期重合！交易处理极可能出现问题！！ 靠后日期的记录被覆盖

如果将时间修改为2018-02-15之后，就没有这个问题。

**Comment by refraction-ray** [comment]
这个是正常的，定投日期是按周直接生成的。但交易时发现那天恰好是节假日（春节），就会往后移到下面第一个交易日，但那天碰巧是一周后，就是说两次定投安排重叠了，只算了一次，问题不大

**Comment by bobbypiggy** [comment]
好，我再测试一下详细数据。
