### ISSUE TITLE
请问是否支持场内ETF？

### ISSUE THREAD

**Issue by adamwuyu** [refraction-ray/xalpha#94]
看了诞生记和设计哲学，讲的是针对场外基金的。请问对中间费用很低的场内ETF是否适用？如果适用，在使用时要注意什么呢？

**Comment by refraction-ray** [comment]
场内基金（其实场内的股票，可转债也包括）都是支持的。
如果只是想看查看实时或者历史k线数据，可以分别使用`xa.get_rt("SH512400")`，`xa.get_daily("SH512400")`的 API。
如果是实盘交易，想要和基金一样记账汇总和分析，可以参考[场内记账单的文档](https://xalpha.readthedocs.io/en/latest/advance.html#id11)
对于其他场外基金用 ``xa.fundinfo("F123456")`` 的场合，大多数可以用 ``xa.vinfo("SH512400", start="2018-01-01")`` 代替

**Comment by adamwuyu** [comment]
多谢大佬，这就研究研究
