### ISSUE TITLE
xa.misc.get_fund_list 接口测试问题

### ISSUE THREAD

**Issue by bobbypiggy** [refraction-ray/xalpha#97]
for i in ("hh", "zq", "zs", "gp", "qdii", 'lof', "fof"):
    p = xa.misc.get_fund_list(i)
    print("the {} number is: {}".format(i, len(p)))

the hh number is: 3737
**the zq number is: 1898**
the zs number is: 1064
the gp number is: 1412
the qdii number is: 173
the lof number is: 331
the fof number is: 153

对比网站上查询到到信息：
http://fund.eastmoney.com/data/fundranking.html#tall;c0;r;s6yzf;pn50;ddesc;qsd20200214;qed20210214;qdii;zq;gg;gzbd;gzfs;bbzt;sfbb

其他总数都对，就是“债券型”对总数不对，网站是1928，上面调用接口统计出来是1898.

**Comment by refraction-ray** [comment]
这个还真不清楚，也许可以比较下，究竟差了那些

**Comment by bobbypiggy** [comment]
好，我抽空研究一下；

**Comment by bobbypiggy** [comment]
今天测试了一下，每类都不一致，检查了一下数据，感觉还是网页的标题内容更新不及时。
http://fund.eastmoney.com/data/fundranking.html#tall;c0;r;s6yzf;pn50;ddesc;qsd20200301;qed20210301;qdii;zq;gg;gzbd;gzfs;bbzt;sfbb
