### ISSUE TITLE
Total Annualized Returns 策略年化收益讨论

### ISSUE THREAD

**Issue by bobbypiggy** [refraction-ray/xalpha#98]
Total Annualized Returns 策略年化收益公式如下：
Total Annualized Returns=Rp=((1+P)**(250/n)−1)∗100%

P=策略收益
n=策略执行天数

xalpha的源码计算如下：
@staticmethod
    def annualized_returns(price, start, date=yesterdayobj()):
        """
        :param price: price table of info().price
        :param start: datetime obj for starting date of calculation
        :param date: datetime obj for ending date of calculation
        :returns: float, annualized returns of the price table
        """
        datediff = (price[price["date"] <= date].iloc[-1].date - start).days
        totreturn = (
            price[price["date"] <= date].iloc[-1].netvalue - price.iloc[0].netvalue
        ) / price.iloc[0].netvalue
        **return round((1 + totreturn) ** (365 / datediff) - 1, 4)**

想请教一下，这里的365为什么不是250呢？
另外参考quantopian的公式:
http://quantopian.github.io/empyrical/_modules/empyrical/stats.html#annual_return

**Comment by refraction-ray** [comment]
因为这里本来的日期差也是包含了节假日的，如果 datediff 的计算舍弃了节假日，就应该是 250 天了

**Comment by bobbypiggy** [comment]
我的意思是问“ return round((1 + totreturn) ** (365 / datediff) - 1, 4)

为什么不是写成return round((1 + totreturn) ** (250 / datediff) - 1, 4)呢？

**Comment by refraction-ray** [comment]
我的回答就是在解释这个问题

**Comment by bobbypiggy** [comment]
理解了，那我修改一下，把datediff里的节假日去掉；

**Comment by refraction-ray** [comment]
这个部分也没什么需要修改的吧，datediff 包括节假日也没什么问题，只要除以 365，对应的还是正确的年化
